## 라이브러리 호출 및 데이터 로드

In [95]:
# 라이브러리 호출
import pandas as pd
import numpy as np
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import rcParams
import platform
import ast
from collections import Counter
import json

warnings.filterwarnings('ignore')

# 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # Mac
    plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['axes.unicode_minus'] = False

# 컬럼 너비 제한 해제
pd.set_option('display.max_colwidth', None)

In [ ]:
# 데이터 로드
full_game_1 = pd.read_csv('./게임단위_게임데이터_상위랭커보존-데이터복구완료.csv')
df_all_match_4 = full_game_1.copy()

champions_raw = pd.read_csv('./tft_game_dataset/TFT_Champion_CurrentVersion.csv')
champions = champions_raw.copy()

items_raw = pd.read_csv('./tft_game_dataset/TFT_Item_CurrentVersion.csv')
items_table = items_raw.copy()

In [97]:
df_all_match_4.dtypes

gameid                     str
gameduration           float64
level                    int64
lastround                int64
ranked                   int64
ingameduration         float64
combination                str
champion                   str
tier                       str
player_cnt               int64
season                     str
user_id                    str
flag_1                    bool
flag_2                    bool
mix_flag                   str
combination_rebuild        str
dtype: object

In [98]:
df_all_match_4

,gameid,gameduration,level,lastround,ranked,ingameduration,combination,champion,tier,player_cnt,season,user_id,flag_1,flag_2,mix_flag,combination_rebuild
0,KR_4291707834,1963.905273,6,27,5,1390.165771,"{""Cybernetic"": 1, ""Demolitionist"": 1, ""Infiltrator"": 1, ""Rebel"": 1, ""Set3_Brawler"": 1, ""Set3_Celestial"": 1, ""Set3_Void"": 1, ""Sniper"": 1}","{'Ziggs': {'items': [7], 'star': 1}, 'Ashe': {'items': [9], 'star': 1}, 'ChoGath': {'items': [6], 'star': 1}, 'Ekko': {'items': [1], 'star': 1}}",platinum,8,season 3,KR-USER-1,False,False,normal,"{""Cybernetic"": 1, ""Demolitionist"": 1, ""Infiltrator"": 1, ""Rebel"": 1, ""Set3_Brawler"": 1, ""Set3_Celestial"": 1, ""Set3_Void"": 1, ""Sniper"": 1}"
1,KR_4291707834,1963.905273,8,37,3,1891.282715,"{""Blaster"": 1, ""Chrono"": 1, ""Cybernetic"": 4, ""Demolitionist"": 1, ""Rebel"": 1, ""Set3_Blademaster"": 2, ""Set3_Brawler"": 1, ""Set3_Sorcerer"": 1, ""Set3_Void"": 1, ""Valkyrie"": 1, ""Vanguard"": 2}","{'Ziggs': {'items': [24], 'star': 3}, 'Fiora': {'items': [37], 'star': 2}, 'Leona': {'items': [36, 24], 'star': 2}, 'Lucian': {'items': [], 'star': 2}, 'Vi': {'items': [5], 'star': 2}, 'Kayle': {'items': [], 'star': 2}, 'WuKong': {'items': [3, 67], 'star': 2}, 'VelKoz': {'items': [4], 'star': 2}}",platinum,8,season 3,KR-USER-2,False,False,normal,"{""Blaster"": 1, ""Chrono"": 1, ""Cybernetic"": 4, ""Demolitionist"": 1, ""Rebel"": 1, ""Set3_Blademaster"": 2, ""Set3_Brawler"": 1, ""Set3_Sorcerer"": 1, ""Set3_Void"": 1, ""Valkyrie"": 1, ""Vanguard"": 2}"
2,KR_4291707834,1963.905273,6,25,7,1279.461060,"{""Blaster"": 1, ""Cybernetic"": 1, ""DarkStar"": 2, ""Infiltrator"": 1, ""Mercenary"": 1, ""Set3_Blademaster"": 1, ""Set3_Mystic"": 1, ""Valkyrie"": 1}","{'Fiora': {'items': [1], 'star': 1}, 'Shaco': {'items': [6], 'star': 1}, 'Karma': {'items': [4], 'star': 1}, 'MissFortune': {'items': [3], 'star': 1}}",platinum,8,season 3,KR-USER-3,False,False,normal,"{""Blaster"": 1, ""Cybernetic"": 1, ""DarkStar"": 2, ""Infiltrator"": 1, ""Mercenary"": 1, ""Set3_Blademaster"": 1, ""Set3_Mystic"": 1, ""Valkyrie"": 1}"
3,KR_4291707834,1963.905273,7,38,2,1955.608521,"{""DarkStar"": 1, ""Protector"": 2, ""Set3_Blademaster"": 1, ""Set3_Celestial"": 5, ""Set3_Mystic"": 1, ""Sniper"": 1, ""StarGuardian"": 2, ""Vanguard"": 2}","{'Poppy': {'items': [], 'star': 2}, 'Xayah': {'items': [19, 23, 19], 'star': 3}, 'Rakan': {'items': [], 'star': 2}, 'XinZhao': {'items': [16], 'star': 2}, 'Mordekaiser': {'items': [35, 67, 33], 'star': 3}, 'Ashe': {'items': [], 'star': 2}, 'Soraka': {'items': [68, 47], 'star': 2}}",platinum,8,season 3,KR-USER-4,False,False,normal,"{""DarkStar"": 1, ""Protector"": 2, ""Set3_Blademaster"": 1, ""Set3_Celestial"": 5, ""Set3_Mystic"": 1, ""Sniper"": 1, ""StarGuardian"": 2, ""Vanguard"": 2}"
4,KR_4291707834,1963.905273,8,38,1,1955.608521,"{""Blaster"": 1, ""Chrono"": 5, ""DarkStar"": 3, ""Protector"": 1, ""Set3_Blademaster"": 1, ""Set3_Brawler"": 1, ""Set3_Sorcerer"": 2, ""Sniper"": 2}","{'TwistedFate': {'items': [36, 27], 'star': 3}, 'Caitlyn': {'items': [49, 29], 'star': 2}, 'JarvanIV': {'items': [56], 'star': 2}, 'Blitzcrank': {'items': [15], 'star': 2}, 'Shen': {'items': [77, 6], 'star': 2}, 'Ezreal': {'items': [16], 'star': 2}, 'Lux': {'items': [], 'star': 2}, 'Jhin': {'items': [], 'star': 2}}",platinum,8,season 3,KR-USER-5,False,False,normal,"{""Blaster"": 1, ""Chrono"": 5, ""DarkStar"": 3, ""Protector"": 1, ""Set3_Blademaster"": 1, ""Set3_Brawler"": 1, ""Set3_Sorcerer"": 2, ""Sniper"": 2}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396483,KR_4357265434,2094.518555,7,33,4,1838.332764,"{""DarkStar"": 2, ""Demolitionist"": 2, ""Infiltrator"": 4, ""MechPilot"": 3, ""Set3_Sorcerer"": 2, ""Set3_Void"": 1, ""Valkyrie"": 1}","{'KhaZix': {'items': [67, 26, 56], 'star': 2}, 'KaiSa': {'items': [38, 44, 33], 'star': 2}, 'Annie': {'items': [], 'star': 3}, 'Shaco': {'items': [45, 29, 16], 'star': 3}, 'Rumble': {'items': [55, 66, 77], 'star': 2}, 'Lux': {'items': [46], 'star': 2}, 'Fizz': {'items': [], 'star': 2}}",challenger,8,season 3,KR-USER-399994,False,False,normal,"{""DarkStar"": 2, ""Demolitionist"": 2, ""Infiltrator"": 4, ""MechPilot"": 3, ""Set3_Sorcerer"": 2, ""Set3_Void"": 1, ""Valkyrie"": 1}"
396484,KR_4357265434,2094.518555,8,33,5,1837.548096,"{""Blaster"": 1, ""Chrono"": 2, ""Cybernetic"": 6, ""Infiltrator"": 2, ""ManaReaver"": 2, ""Set3_Blademaster"": 3, ""Set3_Brawler"": 1, ""Vanguard"": 1}","{'Fiora': {'items': [35], 'star': 2}, 'Leona': {'items': [22], 'star': 1}, 'Shen': {'items': [], 'star': 1}, 'Lucian': {'items': [57, 2, 23], 'star': 2}, 'Vi': {'items': [67, 36], 'star': 2}, 'Irelia': {'items': [29, 28, 15], 'star': 2}, 'Thresh': {'items': [57], 'star': 2}, 'Ekko': {'items': [35, 15, 2], 'star': 2}}",challenger,8,season 3,KR-USER-399995,False,False,normal,"{""Blaster"": 1, ""Chrono"": 2, ""Cybernetic"": 6, ""Infiltrator"": 2, ""ManaReaver"": 2, ""Set3_Blademaster"": 3, ""Set3_Brawler"": 1, ""Vanguard"": 1}"
396485,KR_4357265434,2094.518555,9,33,6,1833.472046,"{""Chrono"": 2, ""Cybernetic"": 1, ""Demolitionist"": 2, ""Infiltrator"": 2, ""MechPilot"": 1, ""Mercenary"": 1, ""Rebel"": 1, ""Set3_Brawler"": 4, ""Set3_Sorcerer"": 2, ""Set3_Void"": 3, ""SpacePirate"": 1}","{'TwistedFate': {'items': [], 'star': 2}, 'Malphite': {'items': [], 'star': 2}, 'KhaZix': {'items': [19, 49, 22], 'star': 3}, 'Blitzcrank': {'items': [], 'star': 2}, 'Vi': {'items': [45, 45, 77], 'star': 2}, 'ChoGath': {'items': [35, 35, 39], 'star': 2}, 'VelKoz': {'items': [69, 37, 38], 'star': 2}, 'Fizz': {'items': [67], 'star': 1}, 'Gangplank': {'items': [], 'star': 1}}",challenger,8,season 3,KR-USER-399996,False,False,normal,"{""Chrono"": 2, ""Cybernetic"": 1, ""Demolitionist"": 2, ""Infiltrator"": 2, ""MechPilot"": 1, ""Mercenary"": 1, ""Rebel"": 1, ""Set3_Brawler"": 4, ""Set3_Sorcerer"": 2, ""Set3_Void"": 3, ""SpacePirate"": 1}"
396486,KR_4357265434,2094.518555,8,31,7,1730.829712,"{""Blaster"": 4, ""Chrono"": 2, ""Cybernetic"": 1, ""Mercenary"": 1, ""Protector"": 1, ""Rebel"": 2, ""Set3_Brawler"": 4, ""Set3_Void"": 1, ""SpacePirate"": 1, ""Valkyrie"": 1}","{'Malphite': {'items': [], 'star': 1}, 'Graves': {'items': [], 'star': 2}, 'Blitzcrank': {'items': [], 'star': 1}, 'Ezreal': {'items': [57, 22, 78], 'star': 2}, 'Vi': {'items': [], 'star': 2}, 'Jinx': {'items': [19, 12, 19], 'star': 2}, 'ChoGath': {'items': [67], 'star': 2}, 'MissFortune': {'items': [44, 29, 14], 'star': 1}}",challenger,8,season 3,KR-USER-399997,False,False,normal,"{""Blaster"": 4, ""Chrono"": 2, ""Cybernetic"": 1, ""Mercenary"": 1, ""Protector"": 1, ""Rebel"": 2, ""Set3_Brawler"": 4, ""Set3_Void"": 1, ""SpacePirate"": 1, ""Valkyrie"": 1}"
396487,KR_4357265434,2094.518555,6,27,8,1480.288086,"{""ManaReaver"": 2, ""Protector"": 2, ""Set3_Celestial"": 4, ""Sniper"": 1, ""SpacePirate"": 2, ""Vanguard"": 1}","{'Darius': {'items': [14, 33, 36], 'star': 2}, 'Rakan': {'items': [69], 'star': 3}, 'XinZhao': {'items': [1], 'star': 3}, 'Jayce': {'items': [37, 15, 39], 'star': 2}, 'Kassadin': {'items': [26], 'star': 2}, 'Ashe': {'items': [], 'star': 2}}",challenger,8,season 3,KR-USER-399998,False,False,normal,"{""ManaReaver"": 2, ""Protector"": 2, ""Set3_Celestial"": 4, ""Sniper"": 1, ""SpacePirate"": 2, ""Vanguard"": 1}"

In [99]:
champions.dtypes

name                   str
cost                 int64
health               int64
defense              int64
attack               int64
attack_range         int64
speed_of_attack    float64
dps                  int64
skill_name             str
skill_cost             str
origin                 str
class                  str
dtype: object

---
## 1. 시너지명 정리
- 시너지명에 'Set3_'가 포함된 경우, 삭제

In [100]:
#데이터 type 변환

# combination 컬럼 형변환
df_all_match_4['combination'] = df_all_match_4['combination'].apply(ast.literal_eval)

# champion 컬럼 형변환
df_all_match_4['champion'] = df_all_match_4['champion'].apply(ast.literal_eval)

# combination_rebuild 컬럼 형변환
df_all_match_4['combination_rebuild'] = df_all_match_4['combination_rebuild'].apply(ast.literal_eval)

In [101]:
# 형변환 후 데이터 타입 확인
type(df_all_match_4['combination_rebuild'].iloc[0]) # dict
type(df_all_match_4['champion'].iloc[0]) # dict
type(df_all_match_4['combination_rebuild'].iloc[0]) # dict

dict

In [102]:
# 전체 키 목록 확인하는 함수 정의
# set(): 중복을 허용하지 않는 자료형(집합)
# .update(): set에 여러 값을 한 번에 추가하는 메서드
def get_all_keys(df, col):
    all_keys = set()
    for value in df[col]:
        all_keys.update(value.keys())
    return all_keys

# 함수 실행 (접두사 'Set3_' 제거하기 전)
print(get_all_keys(df_all_match_4, 'combination_rebuild'))

{'Protector', 'Set3_Blademaster', 'Infiltrator', 'Chrono', 'Rebel', 'DarkStar', 'Set3_Sorcerer', 'Set3_Celestial', 'MechPilot', 'Blaster', 'Valkyrie', 'Mercenary', 'ManaReaver', 'Set3_Mystic', 'SpacePirate', 'Starship', 'Vanguard', 'Set3_Void', 'Sniper', 'StarGuardian', 'Set3_Brawler', 'Cybernetic', 'Demolitionist'}

In [103]:
# 접두사인 'Set3_'를 삭제하는 함수 정의
def remove_set3_prefix(x):
    result = {}
    for key, value in x.items():
        if 'Set3_' in key:
            new_key = key.replace('Set3_', '')
        else:
            new_key = key
        result[new_key] = value
    return result

In [104]:
# 정의한 함수를 사용해 시너지명 정리
# apply(): 행마다 함수를 적용함
df_all_match_4['combination_rebuild'] = df_all_match_4['combination_rebuild'].apply(remove_set3_prefix)

In [105]:
# 접두사 'Set3_' 제거한 결과 확인
print(get_all_keys(df_all_match_4, 'combination_rebuild'))

{'Celestial', 'Void', 'Protector', 'Blademaster', 'Infiltrator', 'Mystic', 'Chrono', 'Rebel', 'DarkStar', 'MechPilot', 'Blaster', 'Valkyrie', 'Mercenary', 'ManaReaver', 'SpacePirate', 'Brawler', 'Starship', 'Vanguard', 'Sniper', 'Sorcerer', 'StarGuardian', 'Cybernetic', 'Demolitionist'}

---
## 2. 비활성화된 시너지 삭제
- 게임이 진행되는 동안, 활성화되지 않은 시너지 정보 삭제

In [106]:
# 시너지별 활성화 기준(Threshold) 정의
synergy_thresholds = {
    # 직업 시너지
    'Blademaster': [3, 6, 9],
    'ManaReaver': [2],
    'Sorcerer': [2, 4, 6, 8],
    'Vanguard': [2, 4],
    'Protector': [2, 4, 6],
    'Mystic': [2, 4],
    'Brawler': [2, 4],
    'Mercenary': [1],
    'Starship': [1],
    'Infiltrator': [2, 4, 6],
    'Sniper': [2],
    'Blaster': [2, 4],
    'Demolitionist': [2],
    
    # 계열 시너지
    'Void': [3],
    'MechPilot': [3],
    'Rebel': [3, 6, 9],
    'Valkyrie': [2],
    'StarGuardian': [3, 6],
    'Cybernetic': [3, 6],
    'Chrono': [2, 4, 6],
    'DarkStar': [3, 6, 9],
    'SpacePirate': [2, 4],
    'Celestial': [2, 4, 6]
}

In [107]:
# 활성화 레벨 계산 함수 정의
def get_active_level(count, thresholds):
    active = 0
    for t in thresholds:
        if count >= t:
            active = t
        else:
            break
    return active

# 딕셔너리(dict) 형태로 활성화된 시너지만 반환하는 함수 정의
def parse_active_synergies_to_dict(comb_dict):
    # 데이터가 이미 딕셔너리 형태이므로 ast.literal_eval 불필요. 빈 딕셔너리인지 확인
    if not isinstance(comb_dict, dict) or not comb_dict:
        return {}
        
    active_res = {}
    for syn, count in comb_dict.items():
        if syn in synergy_thresholds:
            active_lvl = get_active_level(count, synergy_thresholds[syn])
            # 활성화 레벨이 0보다 큰 경우(최소 조건 달성)에만 딕셔너리에 추가
            if active_lvl > 0:
                active_res[syn] = active_lvl
                
    # 결과도 깔끔하게 딕셔너리 형태로 반환 (json 변환 불필요)
    return active_res

In [108]:
# 'active_synergies' 컬럼을 추가하여 활성화된 시너지 딕셔너리만 따로 확인
df_all_match_4['active_synergies'] = df_all_match_4['combination_rebuild'].apply(parse_active_synergies_to_dict)

In [109]:
# 결과 확인
display(df_all_match_4[['combination_rebuild', 'active_synergies']].head())

,combination_rebuild,active_synergies
0,"{'Cybernetic': 1, 'Demolitionist': 1, 'Infiltrator': 1, 'Rebel': 1, 'Brawler': 1, 'Celestial': 1, 'Void': 1, 'Sniper': 1}",{}
1,"{'Blaster': 1, 'Chrono': 1, 'Cybernetic': 4, 'Demolitionist': 1, 'Rebel': 1, 'Blademaster': 2, 'Brawler': 1, 'Sorcerer': 1, 'Void': 1, 'Valkyrie': 1, 'Vanguard': 2}","{'Cybernetic': 3, 'Vanguard': 2}"
2,"{'Blaster': 1, 'Cybernetic': 1, 'DarkStar': 2, 'Infiltrator': 1, 'Mercenary': 1, 'Blademaster': 1, 'Mystic': 1, 'Valkyrie': 1}",{'Mercenary': 1}
3,"{'DarkStar': 1, 'Protector': 2, 'Blademaster': 1, 'Celestial': 5, 'Mystic': 1, 'Sniper': 1, 'StarGuardian': 2, 'Vanguard': 2}","{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}"
4,"{'Blaster': 1, 'Chrono': 5, 'DarkStar': 3, 'Protector': 1, 'Blademaster': 1, 'Brawler': 1, 'Sorcerer': 2, 'Sniper': 2}","{'Chrono': 4, 'DarkStar': 3, 'Sorcerer': 2, 'Sniper': 2}"

---
## 3. champion 테이블 전처리

### 3-1. champion 테이블 내 class 컬럼에 존재하는 오타 수정
- `Infiltrato` → `Infiltrator` 오타 수정

In [110]:
# Infiltrator 관련 전체 조회 (오타 포함)
infiltrator_all = champions[
    champions['class'].str.contains('Infiltrat', case=False, na=False)
][['name', 'class']]

print(f"Infiltrat* 포함 Champion 개수: {len(infiltrator_all)}")
print(infiltrator_all)

Infiltrat* 포함 Champion 개수: 5
      name            class
18   shaco  ['Infiltrator']
30    ekko   ['Infiltrato']
45   kaisa  ['Infiltrator']
46  khazix  ['Infiltrator']
51    fizz  ['Infiltrator']

In [111]:
# 정상 값만 출력(Infiltrator)
infiltrator_correct = champions[
    champions['class'].str.contains(r'\bInfiltrator\b', case=False, na=False)
][['name', 'class']]
print(f"\n정상 Infiltrator 개수: {len(infiltrator_correct)}")

정상 Infiltrator 개수: 4

In [112]:
# 오타만 따로 추출 (정상값 제외)
infiltrator_typo = infiltrator_all[
    ~infiltrator_all['class'].str.contains(r'\bInfiltrator\b', case=False, na=False)
]

print(f"\n오타 의심 항목")
print(infiltrator_typo)

오타 의심 항목
    name           class
30  ekko  ['Infiltrato']

In [113]:
# 오타 수정
champions['class'] = champions['class'].str.replace(
    r'\bInfiltrato\b', 'Infiltrator', regex=True
)

In [114]:
# 수정 후 확인
infiltrator_after = champions[champions['class'].str.contains('Infiltrator', na=False)][['name', 'class']]
print(f"Infiltrator 포함 Champion 개수: {len(infiltrator_after)}")
print(infiltrator_after)

Infiltrator 포함 Champion 개수: 5
      name            class
18   shaco  ['Infiltrator']
30    ekko  ['Infiltrator']
45   kaisa  ['Infiltrator']
46  khazix  ['Infiltrator']
51    fizz  ['Infiltrator']

### 3-2. 컬럼명 및 해당값 소문자로 변환

In [115]:
# 컬럼명 소문자 통일
champions.columns = champions.columns.str.lower()

champions.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             52 non-null     str
 1   cost             52 non-null     int64
 2   health           52 non-null     int64
 3   defense          52 non-null     int64
 4   attack           52 non-null     int64
 5   attack_range     52 non-null     int64
 6   speed_of_attack  52 non-null     float64
 7   dps              52 non-null     int64
 8   skill_name       52 non-null     str
 9   skill_cost       52 non-null     str
 10  origin           52 non-null     str
 11  class            52 non-null     str
dtypes: float64(1), int64(6), str(5)
memory usage: 5.0 KB

### 3-3. 새로운 데이프레임 제작
- match 데이터에서 챔피언과 관련된 정보만 담은 데이터 프레임 제작 (`df_match`)

In [116]:
# match 데이터에서 챔피언과 관련된 정보만 담은 데이터 프레임 제작
champion_data = []

# 매치 데이터에서 가져올 컬럼 목록
for idx, row in df_all_match_4.iterrows():
    # row는 현재 행의 데이터를 담고 있는 Series
    game_id = row['gameid']
    tier = row['tier']
    ranked = row['ranked']
    user_id = row['user_id']
    flag_1 = row['flag_1']
    flag_2 = row['flag_2']
    
    # 각 챔피언별 행 생성
    for champion_name, champion_info in row['champion'].items():
        items = champion_info.get('items', [])  # 아이템 리스트
        star = champion_info.get('star', 0)     # 챔피언 레벨
        
        champion_data.append({
            'gameid': game_id,
            'user_id': user_id,
            'tier': tier,
            'ranked': ranked,
            'champion_name': champion_name,
            'items': items,    
            'star': star,
            'flag_1': flag_1,
            'flag_2': flag_2
        })

In [117]:
# 데이터프레임 생성
champion_table = pd.DataFrame(champion_data)

In [118]:
# 결과 확인
champion_table.head(20)

,gameid,user_id,tier,ranked,champion_name,items,star,flag_1,flag_2
0,KR_4291707834,KR-USER-1,platinum,5,Ziggs,[7],1,False,False
1,KR_4291707834,KR-USER-1,platinum,5,Ashe,[9],1,False,False
2,KR_4291707834,KR-USER-1,platinum,5,ChoGath,[6],1,False,False
3,KR_4291707834,KR-USER-1,platinum,5,Ekko,[1],1,False,False
4,KR_4291707834,KR-USER-2,platinum,3,Ziggs,[24],3,False,False
5,KR_4291707834,KR-USER-2,platinum,3,Fiora,[37],2,False,False
6,KR_4291707834,KR-USER-2,platinum,3,Leona,"[36, 24]",2,False,False
7,KR_4291707834,KR-USER-2,platinum,3,Lucian,[],2,False,False
8,KR_4291707834,KR-USER-2,platinum,3,Vi,[5],2,False,False
9,KR_4291707834,KR-USER-2,platinum,3,Kayle,[],2,False,False
10,KR_4291707834,KR-USER-2,platinum,3,WuKong,"[3, 67]",2,False,False
11,KR_4291707834,KR-USER-2,platinum,3,VelKoz,[4],2,False,False
12,KR_4291707834,KR-USER-3,platinum,7,Fiora,[1],1,False,False
13,KR_4291707834,KR-USER-3,platinum,7,Shaco,[6],1,False,False
14,KR_4291707834,KR-USER-3,platinum,7,Karma,[4],1,False,False
15,KR_4291707834,KR-USER-3,platinum,7,MissFortune,[3],1,False,False
16,KR_4291707834,KR-USER-4,platinum,2,Poppy,[],2,False,False
17,KR_4291707834,KR-USER-4,platinum,2,Xayah,"[19, 23, 19]",3,False,False
18,KR_4291707834,KR-USER-4,platinum,2,Rakan,[],2,False,False
19,KR_4291707834,KR-USER-4,platinum,2,XinZhao,[16],2,False,False

In [119]:
# Champion 테이블에 Champions 파일의 정보 추가
# 챔피언의 이름을 소문자로 통일 
champion_table['champion_name'] = champion_table['champion_name'].str.strip().str.lower()
champions['name'] = champions['name'].str.strip().str.lower()

# champion_table과 champions 테이블 merge
champion_with_details = champion_table.merge(
    champions[['name', 'cost', 'origin', 'class']],
    left_on='champion_name',  
    right_on='name',
    how='left'  
)

In [120]:
# 결과 확인
champion_with_details.head(20)

,gameid,user_id,tier,ranked,champion_name,items,star,flag_1,flag_2,name,cost,origin,class
0,KR_4291707834,KR-USER-1,platinum,5,ziggs,[7],1,False,False,ziggs,1,Rebel,['Demolitionist']
1,KR_4291707834,KR-USER-1,platinum,5,ashe,[9],1,False,False,ashe,3,Celestial,['Sniper']
2,KR_4291707834,KR-USER-1,platinum,5,chogath,[6],1,False,False,chogath,4,Void,['Brawler']
3,KR_4291707834,KR-USER-1,platinum,5,ekko,[1],1,False,False,ekko,5,Cybernetic,['Infiltrator']
4,KR_4291707834,KR-USER-2,platinum,3,ziggs,[24],3,False,False,ziggs,1,Rebel,['Demolitionist']
5,KR_4291707834,KR-USER-2,platinum,3,fiora,[37],2,False,False,fiora,1,Cybernetic,['Blademaster']
6,KR_4291707834,KR-USER-2,platinum,3,leona,"[36, 24]",2,False,False,leona,1,Cybernetic,['Vanguard']
7,KR_4291707834,KR-USER-2,platinum,3,lucian,[],2,False,False,lucian,2,Cybernetic,['Blaster']
8,KR_4291707834,KR-USER-2,platinum,3,vi,[5],2,False,False,vi,3,Cybernetic,['Brawler']
9,KR_4291707834,KR-USER-2,platinum,3,kayle,[],2,False,False,kayle,4,Valkyrie,['Blademaster']
10,KR_4291707834,KR-USER-2,platinum,3,wukong,"[3, 67]",2,False,False,wukong,4,Chrono,['Vanguard']
11,KR_4291707834,KR-USER-2,platinum,3,velkoz,[4],2,False,False,velkoz,4,Void,['Sorcerer']
12,KR_4291707834,KR-USER-3,platinum,7,fiora,[1],1,False,False,fiora,1,Cybernetic,['Blademaster']
13,KR_4291707834,KR-USER-3,platinum,7,shaco,[6],1,False,False,shaco,3,Dark Star,['Infiltrator']
14,KR_4291707834,KR-USER-3,platinum,7,karma,[4],1,False,False,karma,3,Dark Star,['Mystic']
15,KR_4291707834,KR-USER-3,platinum,7,missfortune,[3],1,False,False,missfortune,5,Valkyrie,"['Mercenary', 'Blaster']"
16,KR_4291707834,KR-USER-4,platinum,2,poppy,[],2,False,False,poppy,1,Star Guardian,['Vanguard']
17,KR_4291707834,KR-USER-4,platinum,2,xayah,"[19, 23, 19]",3,False,False,xayah,1,Celestial,['Blademaster']
18,KR_4291707834,KR-USER-4,platinum,2,rakan,[],2,False,False,rakan,2,Celestial,['Protector']
19,KR_4291707834,KR-USER-4,platinum,2,xinzhao,[16],2,False,False,xinzhao,2,Celestial,['Protector']

In [121]:
champion_with_details.dtypes
# type(champion_with_details['items'].iloc[0]) # list
# type(champion_with_details['class'].iloc[0]) # str

gameid              str
user_id             str
tier                str
ranked            int64
champion_name       str
items            object
star              int64
flag_1             bool
flag_2             bool
name                str
cost              int64
origin              str
class               str
dtype: object

In [122]:
# Class 칼럼 값 표기 정제
# 리스트 문자열 변환
champion_with_details['class'] = champion_with_details['class'].apply(
    lambda x: ', '.join(ast.literal_eval(x)) if isinstance(x, str) else ', '.join(x if isinstance(x, list) else [])
)

In [ ]:
champion_with_details

	# KR_4291707834	Platinum	7	missfortune	[3]		1	5.0		1.00	missfortune_bullettime	75/175	Valkyrie	Mercenary, Blaster
	# KR_4291614366	Platinum	5	irelia		[5]		2	4.0		0.85	irelia_bladesurge	0/30	Cybernetic	Mana-Reaver, Blademaster
	# KR_4291614366	Platinum	5	missfortune	[27]	1	5.0		1.00	missfortune_bullettime	75/175	Valkyrie	Mercenary, Blaster
	# KR_4291614366	Platinum	6	irelia		[]		1	4.0		0.85	irelia_bladesurge	0/30	Cybernetic	Mana-Reaver, Blademaster
	# KR_4291614366	Platinum	1	missfortune	[56]	2	5.0		1.00	missfortune_bullettime	75/175	Valkyrie	Mercenary, Blaster

,gameid,user_id,tier,ranked,champion_name,items,star,flag_1,flag_2,name,cost,origin,class
0,KR_4291707834,KR-USER-1,platinum,5,ziggs,[7],1,False,False,ziggs,1,Rebel,Demolitionist
1,KR_4291707834,KR-USER-1,platinum,5,ashe,[9],1,False,False,ashe,3,Celestial,Sniper
2,KR_4291707834,KR-USER-1,platinum,5,chogath,[6],1,False,False,chogath,4,Void,Brawler
3,KR_4291707834,KR-USER-1,platinum,5,ekko,[1],1,False,False,ekko,5,Cybernetic,Infiltrator
4,KR_4291707834,KR-USER-2,platinum,3,ziggs,[24],3,False,False,ziggs,1,Rebel,Demolitionist
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3130592,KR_4357265434,KR-USER-399998,challenger,8,rakan,[69],3,False,False,rakan,2,Celestial,Protector
3130593,KR_4357265434,KR-USER-399998,challenger,8,xinzhao,[1],3,False,False,xinzhao,2,Celestial,Protector
3130594,KR_4357265434,KR-USER-399998,challenger,8,jayce,"[37, 15, 39]",2,False,False,jayce,3,Space Pirate,Vanguard
3130595,KR_4357265434,KR-USER-399998,challenger,8,kassadin,[26],2,False,False,kassadin,3,Celestial,Mana-Reaver
3130596,KR_4357265434,KR-USER-399998,challenger,8,ashe,[],2,False,False,ashe,3,Celestial,Sniper

### 3-4. combination 정보가 담긴 새로운 데이터프레임 제작

In [128]:
# Combination 테이블 생성
combination_data = []

# 매치 데이터에서 가져올 컬럼 목록
for idx, row in df_all_match_4.iterrows():
    # row는 현재 행의 데이터를 담고 있는 Series
    game_id = row['gameid']
    tier = row['tier']
    ranked = row['ranked']
    user_id = row['user_id']
    flag_1 = row['flag_1']
    flag_2 = row['flag_2']
    active_synergies = row['active_synergies']

    for synergy, synergy_val in row['combination_rebuild'].items():

        combination_data.append({
            'gameid': game_id,
            'user_id': user_id,
            'tier': tier,
            'ranked': ranked,
            'flag_1': flag_1,
            'flag_2': flag_2,
            'active_synergies': active_synergies,
            'synergy': synergy,
            'synergy_val': synergy_val
        })

combination_table = pd.DataFrame(combination_data)

In [129]:
combination_table

,gameid,user_id,tier,ranked,flag_1,flag_2,active_synergies,synergy,synergy_val
0,KR_4291707834,KR-USER-1,platinum,5,False,False,{},Cybernetic,1
1,KR_4291707834,KR-USER-1,platinum,5,False,False,{},Demolitionist,1
2,KR_4291707834,KR-USER-1,platinum,5,False,False,{},Infiltrator,1
3,KR_4291707834,KR-USER-1,platinum,5,False,False,{},Rebel,1
4,KR_4291707834,KR-USER-1,platinum,5,False,False,{},Brawler,1
...,...,...,...,...,...,...,...,...,...
3361550,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Protector,2
3361551,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Celestial,4
3361552,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Sniper,1
3361553,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",SpacePirate,2
3361554,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Vanguard,1

In [131]:
type(combination_table['active_synergies'].iloc[0])

dict

### active synergies에 해당하는 것만 explode table에 남도록 필터

In [135]:
combination_filtered_table = combination_table[
    combination_table.apply(
        lambda row: row['synergy'] in row['active_synergies'].keys() 
        if row['active_synergies'] else False,
        axis=1
    )
]

In [136]:
combination_filtered_table

,gameid,user_id,tier,ranked,flag_1,flag_2,active_synergies,synergy,synergy_val
10,KR_4291707834,KR-USER-2,platinum,3,False,False,"{'Cybernetic': 3, 'Vanguard': 2}",Cybernetic,4
18,KR_4291707834,KR-USER-2,platinum,3,False,False,"{'Cybernetic': 3, 'Vanguard': 2}",Vanguard,2
23,KR_4291707834,KR-USER-3,platinum,7,False,False,{'Mercenary': 1},Mercenary,1
28,KR_4291707834,KR-USER-4,platinum,2,False,False,"{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}",Protector,2
30,KR_4291707834,KR-USER-4,platinum,2,False,False,"{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}",Celestial,5
...,...,...,...,...,...,...,...,...,...
3361545,KR_4357265434,KR-USER-399997,challenger,7,False,False,"{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Brawler': 4}",Brawler,4
3361549,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",ManaReaver,2
3361550,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Protector,2
3361551,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Celestial,4
3361553,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",SpacePirate,2

### combination_filtered_table의 synergy 값과 champion_with_details의 class 일치하는 것끼리 조인 시도
#### 참고. acitve_synergies 칼럼은 최소 활성화 기준 값을 넣어둔 것..

In [137]:
# 
champion_selected = champion_with_details[['gameid', 'user_id', 'class', 'champion_name', 'items', 'star', 'name', 'cost', 'origin']]

result = combination_filtered_table .merge(
    champion_selected,
    left_on=['gameid', 'user_id', 'synergy'],
    right_on=['gameid', 'user_id', 'class'],
    how='inner'
).drop(columns=['class'])

In [138]:
result

,gameid,user_id,tier,ranked,flag_1,flag_2,active_synergies,synergy,synergy_val,champion_name,items,star,name,cost,origin
0,KR_4291707834,KR-USER-2,platinum,3,False,False,"{'Cybernetic': 3, 'Vanguard': 2}",Vanguard,2,leona,"[36, 24]",2,leona,1,Cybernetic
1,KR_4291707834,KR-USER-2,platinum,3,False,False,"{'Cybernetic': 3, 'Vanguard': 2}",Vanguard,2,wukong,"[3, 67]",2,wukong,4,Chrono
2,KR_4291707834,KR-USER-4,platinum,2,False,False,"{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}",Protector,2,rakan,[],2,rakan,2,Celestial
3,KR_4291707834,KR-USER-4,platinum,2,False,False,"{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}",Protector,2,xinzhao,[16],2,xinzhao,2,Celestial
4,KR_4291707834,KR-USER-4,platinum,2,False,False,"{'Protector': 2, 'Celestial': 4, 'Vanguard': 2}",Vanguard,2,poppy,[],2,poppy,1,Star Guardian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2162379,KR_4357265434,KR-USER-399997,challenger,7,False,False,"{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Brawler': 4}",Brawler,4,blitzcrank,[],1,blitzcrank,2,Chrono
2162380,KR_4357265434,KR-USER-399997,challenger,7,False,False,"{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Brawler': 4}",Brawler,4,vi,[],2,vi,3,Cybernetic
2162381,KR_4357265434,KR-USER-399997,challenger,7,False,False,"{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Brawler': 4}",Brawler,4,chogath,[67],2,chogath,4,Void
2162382,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Protector,2,rakan,[69],3,rakan,2,Celestial
2162383,KR_4357265434,KR-USER-399998,challenger,8,False,False,"{'ManaReaver': 2, 'Protector': 2, 'Celestial': 4, 'SpacePirate': 2}",Protector,2,xinzhao,[1],3,xinzhao,2,Celestial

---
## 4. items 테이블 전처리

### 4-1. items 정보가 담긴 새로운 데이터프레임 제작

In [124]:
# item 테이블의 아이템명을 붙여 오기 위해서는 items 칼럼의 리스트를 explode 시켜야함 & 정수형 변환 필요
# 한 캐릭터에 여러 아이템이 사용되어서, 아이템 수만큼 행 증가됨 (따라서 item_count 칼럼 생성할 예정)
# 예시
# | gameId | tier  | Ranked | champion_name  | item_id | item_name | star | item_count |
# |--------|-------|--------|----------------|---------|-----------|------|------------|
# | 1      | Gold  | Ranked | Ahri           | 1       | Sword     | 3    | 1          |
# | 1      | Gold  | Ranked | Ahri           | 2       | Shield    | 3    | 1          |
# | 1      | Gold  | Ranked | Ahri           | 3       | Boots     | 3    | 2          |
# | 2      | Plat  | Ranked | Lux            | 5       | Staff     | 2    | 2          |

In [126]:
# 아이템 이름 매핑을 위해 딕셔너리 생성
item_dict = dict(zip(items_table['id'], items_table['name']))

#Champion 테이블에 Item 정보 추가
champion_table_with_items_name = champion_with_details.copy()

# 아이템 개수 계산
champion_table_with_items_name['item_count'] = champion_table_with_items_name['items'].apply(
    lambda x: len(x) if isinstance(x, list) else 0
)

# explode
champion_table_item_exploded = champion_table_with_items_name.explode('items', ignore_index=True)

# 숫자 변환 
champion_table_item_exploded['item_id'] = pd.to_numeric(
    champion_table_item_exploded['items'], errors='coerce'
).astype('Int64')

# 매핑
champion_table_item_exploded['item_name'] = champion_table_item_exploded['item_id'].map(item_dict)

# # 정리
# champion_table_exploded = champion_table_exploded[[
#     'gameId', 'tier', 'Ranked', 'champion_name', 'item_id', 'item_name', 'star', 'item_count'
# ]]

In [127]:
champion_table_item_exploded

,gameid,user_id,tier,ranked,champion_name,items,star,flag_1,flag_2,name,cost,origin,class,item_count,item_id,item_name
0,KR_4291707834,KR-USER-1,platinum,5,ziggs,7,1,False,False,ziggs,1,Rebel,Demolitionist,1,7,Giant's Belt
1,KR_4291707834,KR-USER-1,platinum,5,ashe,9,1,False,False,ashe,3,Celestial,Sniper,1,9,Sparring Gloves
2,KR_4291707834,KR-USER-1,platinum,5,chogath,6,1,False,False,chogath,4,Void,Brawler,1,6,Negatron Cloak
3,KR_4291707834,KR-USER-1,platinum,5,ekko,1,1,False,False,ekko,5,Cybernetic,Infiltrator,1,1,B.F. Sword
4,KR_4291707834,KR-USER-2,platinum,3,ziggs,24,3,False,False,ziggs,1,Rebel,Demolitionist,1,24,Statikk Shiv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4861828,KR_4357265434,KR-USER-399998,challenger,8,jayce,37,2,False,False,jayce,3,Space Pirate,Vanguard,3,37,Morellonomicon
4861829,KR_4357265434,KR-USER-399998,challenger,8,jayce,15,2,False,False,jayce,3,Space Pirate,Vanguard,3,15,Guardian Angel
4861830,KR_4357265434,KR-USER-399998,challenger,8,jayce,39,2,False,False,jayce,3,Space Pirate,Vanguard,3,39,Jeweled Gauntlet
4861831,KR_4357265434,KR-USER-399998,challenger,8,kassadin,26,2,False,False,kassadin,3,Celestial,Mana-Reaver,1,26,Runaan's Hurricane
4861832,KR_4357265434,KR-USER-399998,challenger,8,ashe,NaN,2,False,False,ashe,3,Celestial,Sniper,0,<NA>,NaN

---
## 5. 데이터프레임 csv파일로 저장