데이터 불러오기

In [33]:
import pandas as pd

df_comb = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
df_user = df_comb.drop_duplicates(subset=['gameid', 'user_id']).copy()

df_match = pd.read_csv('게임단위_게임데이터_상위랭커보존-2차 전처리 완료(match).csv')

전체 경기 수

In [34]:
total_matches = df_user['gameid'].nunique()
print(total_matches)

49561

전체 조합 수

In [35]:
total_combinations = df_user['active_synergies'].nunique()
print(total_combinations)

16587

평균 등수 1위 조합

In [36]:
best_win_comb = df_user[df_user['ranked_1'] == 1]['active_synergies'].value_counts().idxmax()
print(best_win_comb)

{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Rebel': 3, 'Brawler': 4, 'Starship': 1}

순방 비율 1위 조합

In [37]:
comb_counts = df_user['active_synergies'].value_counts()
valid_combs = comb_counts[comb_counts >= 30].index
top4_rates = df_user[df_user['active_synergies'].isin(valid_combs)].groupby('active_synergies')['top4_flag'].mean()
print(top4_rates.idxmax())

{'Blaster': 2, 'Chrono': 2, 'Cybernetic': 6, 'ManaReaver': 2, 'Mercenary': 1, 'Blademaster': 3, 'Brawler': 2, 'Valkyrie': 2}

우승 비율 1위 조합

In [38]:
win_rates = df_user[df_user['active_synergies'].isin(valid_combs)].groupby('active_synergies')['ranked_1'].mean()
print(win_rates.idxmax())

{'Chrono': 2, 'ManaReaver': 2, 'Brawler': 2, 'Celestial': 2, 'Mystic': 2, 'Sorcerer': 2, 'Void': 3}

티어별 평균 최종 레벨

In [39]:
tier_level = df_match.groupby('tier')['level'].mean().sort_values(ascending=False)
print(tier_level)

tier
grand_master    7.895715
challenger      7.892927
diamond         7.856640
master          7.842178
platinum        7.793047
Name: level, dtype: float64

티어별 평균 생존 라운드

In [40]:
tier_level = df_match.groupby('tier')['level'].mean().sort_values(ascending=False)
print(tier_level)

tier_round = df_match.groupby('tier')['lastround'].mean().sort_values(ascending=False)
print(tier_round)

tier
grand_master    7.895715
challenger      7.892927
diamond         7.856640
master          7.842178
platinum        7.793047
Name: level, dtype: float64
tier
challenger      33.751463
grand_master    33.589659
diamond         33.582231
master          33.536586
platinum        33.292009
Name: lastround, dtype: float64

상위 5개 조합 라운드

In [41]:
top5_share = df_user['active_synergies'].value_counts(normalize=True).head(5) * 100
print(top5_share)

active_synergies
{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Brawler': 4}                                                        6.131617
{'Blaster': 4, 'Chrono': 2, 'Mercenary': 1, 'Rebel': 3, 'Brawler': 4, 'Starship': 1}                             2.350432
{'Blaster': 4, 'Chrono': 2, 'Brawler': 4}                                                                        1.821692
{'Blaster': 2, 'Chrono': 4, 'ManaReaver': 2, 'Mercenary': 1, 'Blademaster': 3, 'Celestial': 2, 'Valkyrie': 2}    1.794687
{'Mystic': 2, 'Sorcerer': 4, 'StarGuardian': 6}                                                                  1.761373
Name: proportion, dtype: float64

티어별 챔피언 순방률

In [42]:
import pandas as pd

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
champ_tier_stats = df_champ.groupby(['tier', 'champion_name'])['top4_flag'].mean().reset_index()
champ_tier_stats = champ_tier_stats.sort_values(by=['tier', 'top4_flag'], ascending=[True, False])

display(champ_tier_stats)

           tier champion_name  top4_flag
3    challenger   aurelionsol   0.713287
26   challenger          lulu   0.671342
41   challenger        thresh   0.625937
30   challenger   missfortune   0.603562
47   challenger        xerath   0.602859
..          ...           ...        ...
246    platinum          sona   0.442740
215    platinum        darius   0.442021
237    platinum      masteryi   0.418292
257    platinum         yasuo   0.413999
258    platinum         ziggs   0.403620

[260 rows x 3 columns]

티어별 시너지 순방률

In [43]:
import pandas as pd

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
synergy_tier_stats = df_synergy.groupby(['tier', 'synergy'])['top4_flag'].mean().reset_index()
synergy_tier_stats = synergy_tier_stats.sort_values(by=['tier', 'top4_flag'], ascending=[True, False])

display(synergy_tier_stats)

           tier       synergy  top4_flag
19   challenger      Starship   0.713449
11   challenger     Mercenary   0.600443
12   challenger        Mystic   0.547945
20   challenger      Valkyrie   0.539177
18   challenger  StarGuardian   0.521139
..          ...           ...        ...
107    platinum        Sniper   0.499645
110    platinum  StarGuardian   0.492075
105    platinum     Protector   0.489379
92     platinum   Blademaster   0.489049
113    platinum      Vanguard   0.475118

[115 rows x 3 columns]

티어별 챔피언 우승률

In [44]:
import pandas as pd

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
champ_win_stats = df_champ.groupby(['tier', 'champion_name'])['ranked_1'].mean().reset_index()
champ_win_stats = champ_win_stats.sort_values(by=['tier', 'ranked_1'], ascending=[True, False])

display(champ_win_stats)

           tier champion_name  ranked_1
26   challenger          lulu  0.208599
3    challenger   aurelionsol  0.200767
47   challenger        xerath  0.195279
39   challenger        soraka  0.173313
12   challenger     gangplank  0.170768
..          ...           ...       ...
232    platinum         leona  0.105496
213    platinum       caitlyn  0.102187
258    platinum         ziggs  0.099315
237    platinum      masteryi  0.098000
257    platinum         yasuo  0.095800

[260 rows x 3 columns]

티어별 시너지 우승률

In [45]:
import pandas as pd

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
synergy_win_stats = df_synergy.groupby(['tier', 'synergy'])['ranked_1'].mean().reset_index()
synergy_win_stats = synergy_win_stats.sort_values(by=['tier', 'ranked_1'], ascending=[True, False])

display(synergy_win_stats)

           tier       synergy  ranked_1
19   challenger      Starship  0.201847
12   challenger        Mystic  0.164624
11   challenger     Mercenary  0.151259
13   challenger     Protector  0.145196
10   challenger     MechPilot  0.144889
..          ...           ...       ...
110    platinum  StarGuardian  0.122691
107    platinum        Sniper  0.121645
105    platinum     Protector  0.119690
92     platinum   Blademaster  0.119036
113    platinum      Vanguard  0.116945

[115 rows x 3 columns]

### 그룹 1부터 시작!

### 1번: 특정 시너지 조합은 다른 조합보다 유의미하게 승률이 높다

In [57]:
import pandas as pd
from scipy.stats import chi2_contingency

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
results = []

for syn in df_synergy['synergy'].unique():
    df_synergy['is_target'] = (df_synergy['synergy'] == syn)
    contingency = pd.crosstab(df_synergy['is_target'], df_synergy['ranked_1'])
    
    if contingency.shape == (2, 2):
        chi2, p, dof, expected = chi2_contingency(contingency)
        target_win_rate = df_synergy[df_synergy['is_target'] == True]['ranked_1'].mean()
        other_win_rate = df_synergy[df_synergy['is_target'] == False]['ranked_1'].mean()
        
        results.append({
            'synergy': syn,
            'target_win_rate': target_win_rate,
            'other_win_rate': other_win_rate,
            'p_value': p
        })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

          synergy  target_win_rate  other_win_rate        p_value
22       Starship         0.202457        0.132649  1.908419e-213
15      Mercenary         0.159976        0.132075  1.535654e-181
16         Mystic         0.157119        0.132092  9.308613e-160
4         Brawler         0.120936        0.133770   2.574430e-51
13       Vanguard         0.123166        0.133731   9.118350e-40
0      Cybernetic         0.125467        0.133642   1.251463e-26
8         Blaster         0.125410        0.133558   1.073783e-22
9          Chrono         0.127098        0.133642   2.545038e-21
19    SpacePirate         0.125169        0.133492   5.602869e-20
7          Sniper         0.125352        0.133375   1.007801e-13
3           Rebel         0.127018        0.133433   2.173410e-13
12       Valkyrie         0.138694        0.132819   1.183152e-12
10    Blademaster         0.127834        0.133403   9.348034e-11
18   StarGuardian         0.139428        0.132936   2.259964e-09
5       Celestial         0.137456        0.132885   2.772141e-08
14       DarkStar         0.137238        0.132886   6.400993e-08
1   Demolitionist         0.136138        0.133048   7.111494e-03
11       Sorcerer         0.135158        0.133045   2.491389e-02
21      MechPilot         0.135932        0.133073   3.041137e-02
20     ManaReaver         0.131954        0.133191   1.521145e-01
17      Protector         0.134314        0.133095   2.714310e-01
2     Infiltrator         0.133457        0.133117   7.243104e-01
6            Void         0.133429        0.133116   7.254034e-01

결과 표에서 p_value가 0.05 미만이면서 target_win_rate가 other_win_rate보다 눈에 띄게 높은 시너지들이 바로 우리가 찾는 다른 조합보다 유의미하게 승률이 높은 시너지

### 11번: 특정 아이템 조합이 챔피언 성과에 유의미한 영향을 준다

In [58]:
import pandas as pd
from scipy.stats import ttest_ind

df_item = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_items_1.csv')
results = []

for champ in df_item['champion_name'].unique():
    champ_data = df_item[df_item['champion_name'] == champ]
    
    for item_comb in champ_data['items'].unique():
        target_group = champ_data[champ_data['items'] == item_comb]['ranked']
        other_group = champ_data[champ_data['items'] != item_comb]['ranked']
        
        if len(target_group) > 1 and len(other_group) > 1:
            stat, p = ttest_ind(target_group, other_group, equal_var=False)
            
            results.append({
                'champion': champ,
                'item_combination': item_comb,
                'target_mean_rank': target_group.mean(),
                'other_mean_rank': other_group.mean(),
                'p_value': p
            })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

c:\Users\asdxo\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_axis_nan_policy.py:592: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

,champion,item_combination,target_mean_rank,other_mean_rank,p_value
534,wukong,10006.0,1.000000,4.231079,0.000000e+00
2287,jayce,10006.0,1.000000,4.360357,0.000000e+00
2669,sona,4.0,5.924955,4.410210,1.395351e-192
2662,sona,46.0,4.200105,4.630591,2.002046e-142
1181,jarvaniv,35.0,3.563977,4.305765,1.250426e-119
...,...,...,...,...,...
2754,xerath,46.0,3.885922,3.885125,9.939382e-01
846,xayah,35.0,4.280000,4.277829,9.944491e-01
1721,syndra,99.0,4.397231,4.397662,9.953922e-01
2495,masteryi,44.0,4.833333,4.834293,9.967487e-01
1167,caitlyn,58.0,4.384615,4.383168,9.985203e-01

출력된 데이터프레임에서 p_value가 0.05 미만이면서 target_mean_rank가 other_mean_rank보다 더 낮은(TFT에서 등수는 숫자가 작을수록 좋으므로) 항목들이 바로 그 챔피언에게 다른 템트리보다 통계적으로 확실히 더 좋은 성과를 내게 해주는 특정 아이템 조합

### 13번: 특정 시너지는 1위 달성률이 전체 평균보다 유의미하게 높다

In [59]:
import pandas as pd
from scipy.stats import binomtest

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
overall_win_rate = df_synergy['ranked_1'].mean()
results = []

for syn in df_synergy['synergy'].unique():
    target_data = df_synergy[df_synergy['synergy'] == syn]
    successes = target_data['ranked_1'].sum()
    trials = len(target_data)
    
    if trials > 0:
        res = binomtest(successes, n=trials, p=overall_win_rate, alternative='greater')
        
        results.append({
            'synergy': syn,
            'target_win_rate': successes / trials,
            'overall_win_rate': overall_win_rate,
            'p_value': res.pvalue
        })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

          synergy  target_win_rate  overall_win_rate        p_value
22       Starship         0.202457          0.133131  8.054589e-188
15      Mercenary         0.159976          0.133131  3.806410e-166
16         Mystic         0.157119          0.133131  1.751557e-146
12       Valkyrie         0.138694          0.133131   3.059276e-12
18   StarGuardian         0.139428          0.133131   2.456715e-09
5       Celestial         0.137456          0.133131   3.712249e-08
14       DarkStar         0.137238          0.133131   8.417590e-08
1   Demolitionist         0.136138          0.133131   4.048414e-03
11       Sorcerer         0.135158          0.133131   1.414628e-02
21      MechPilot         0.135932          0.133131   1.626603e-02
17      Protector         0.134314          0.133131   1.392953e-01
2     Infiltrator         0.133457          0.133131   3.644595e-01
6            Void         0.133429          0.133131   3.654871e-01
20     ManaReaver         0.131954          0.133131   9.199903e-01
10    Blademaster         0.127834          0.133131   1.000000e+00
3           Rebel         0.127018          0.133131   1.000000e+00
7          Sniper         0.125352          0.133131   1.000000e+00
13       Vanguard         0.123166          0.133131   1.000000e+00
9          Chrono         0.127098          0.133131   1.000000e+00
4         Brawler         0.120936          0.133131   1.000000e+00
0      Cybernetic         0.125467          0.133131   1.000000e+00
8         Blaster         0.125410          0.133131   1.000000e+00
19    SpacePirate         0.125169          0.133131   1.000000e+00

출력된 표에서 p_value가 0.05 미만이면서 target_win_rate가 overall_win_rate보다 높은 시너지들이 바로 전체 평균을 웃도는 진짜 1위 달성률 1티어 시너지들 일것인데 p벨류가 아까부터 거 참;;

18번: 특정 아이템은 특정 챔피언에게 장착될 때만 유의미한 성과를 보인다

In [60]:
import pandas as pd
from scipy.stats import ttest_ind

df_item = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_items_1.csv')
results = []

for item in df_item['item_name'].dropna().unique():
    item_data = df_item[df_item['item_name'] == item]
    
    for champ in item_data['champion_name'].unique():
        target_group = item_data[item_data['champion_name'] == champ]['ranked']
        other_group = item_data[item_data['champion_name'] != champ]['ranked']
        
        if len(target_group) > 1 and len(other_group) > 1:
            stat, p = ttest_ind(target_group, other_group, equal_var=False)
            
            results.append({
                'item': item,
                'champion': champ,
                'target_mean_rank': target_group.mean(),
                'other_mean_rank': other_group.mean(),
                'p_value': p
            })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

,item,champion,target_mean_rank,other_mean_rank,p_value
2424,Quicksilver,missfortune,3.810582,4.281528,6.643799e-149
546,Tear of the Goddess,sona,5.924955,4.648412,4.109238e-142
1973,Red Buff,lucian,4.338961,3.941945,4.509154e-135
2249,Seraph's Embrace,lucian,5.397690,4.330017,9.484527e-132
1975,Red Buff,missfortune,3.563705,4.064389,1.849187e-125
...,...,...,...,...,...
2534,Trap Claw,wukong,3.776554,3.776270,9.946758e-01
2207,Hextech Gunblade,fiora,4.021220,4.021922,9.948625e-01
1482,Runaan's Hurricane,caitlyn,3.962168,3.962577,9.952472e-01
240,Statikk Shiv,caitlyn,4.006545,4.006355,9.980510e-01
1746,Zeke's Herald,sona,3.746835,3.746707,9.991814e-01

p_value가 0.05 미만이면서 target_mean_rank가 other_mean_rank보다 확연히 낮은(등수가 더 좋은) 항목을 찾으면 됩니다만....

### 19번: 특정 아이템을 보유한 경우 평균 등수가 유의미하게 낮다

In [61]:
import pandas as pd
from scipy.stats import ttest_ind

df_item = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_items_1.csv')
results = []

for item in df_item['item_name'].dropna().unique():
    with_item = df_item[df_item['item_name'] == item]['ranked']
    without_item = df_item[df_item['item_name'] != item]['ranked']
    
    if len(with_item) > 1 and len(without_item) > 1:
        stat, p = ttest_ind(with_item, without_item, equal_var=False)
        
        results.append({
            'item': item,
            'with_item_mean_rank': with_item.mean(),
            'without_item_mean_rank': without_item.mean(),
            'p_value': p
        })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

,item,with_item_mean_rank,without_item_mean_rank,p_value
14,Locket of the Iron Solari,3.678673,4.265795,0.000000e+00
10,Tear of the Goddess,4.712976,4.255910,0.000000e+00
19,Hand Of Justice,3.900369,4.264266,0.000000e+00
17,Redemption,3.781956,4.267131,0.000000e+00
29,Shroud of Stillness,3.462923,4.266290,0.000000e+00
21,Sword Breaker,3.767679,4.263587,0.000000e+00
38,Red Buff,4.019843,4.266076,0.000000e+00
33,Zeke's Herald,3.746708,4.264984,0.000000e+00
49,Trap Claw,3.776282,4.266864,0.000000e+00
48,Rebel Medal,3.674771,4.262213,4.844731e-308
34,Protector's Chestguard,3.657054,4.262275,3.291206e-293
6,Ionic Spark,4.031315,4.265884,3.194596e-291
9,Zephyr,4.010989,4.265228,1.590975e-282
3,B.F. Sword,4.739409,4.257269,4.534105e-264
28,Runaan's Hurricane,3.962570,4.263897,2.988485e-261
26,Frozen Heart,3.997002,4.264463,6.523302e-258
8,Needlessly Large Rod,4.688697,4.257075,1.557291e-256
2,Negatron Cloak,4.677590,4.257636,6.985513e-205
30,Luden's Echo,3.996215,4.263331,1.089537e-196
0,Giant's Belt,4.630235,4.257518,3.044274e-190
50,Demolitionist's Charge,3.915493,4.262542,8.857300e-181
4,Statikk Shiv,4.006358,4.262868,1.668733e-165
24,Recurve Bow,4.567268,4.257444,2.958161e-164
52,Dark Star's Heart,3.774977,4.261447,7.514914e-155
46,Chalice of Favor,4.048571,4.263641,1.327509e-150
16,Celestial Orb,3.908165,4.261765,1.758158e-139
1,Sparring Gloves,4.663611,4.258340,5.822714e-138
42,Hextech Gunblade,4.021917,4.262556,1.077928e-135
7,Chain Vest,4.597721,4.258164,4.521799e-130
40,Blade of the Ruined King,3.859995,4.261229,2.199106e-113
53,Star Guardian's Charm,3.899613,4.261444,1.043067e-108
18,Zz'Rot Portal,4.078366,4.262480,5.476899e-96
44,Infiltrator's Talons,3.978706,4.261535,2.219349e-93
39,Giant Slayer,4.121502,4.262962,5.370527e-93
51,Force of Nature,3.980662,4.261530,7.528784e-92
5,Morellonomicon,4.149370,4.263525,4.739838e-83
35,Titan's Resolve,4.096879,4.262079,1.656463e-73
36,Deathblade,4.093186,4.261395,4.041600e-52
25,Jeweled Gauntlet,4.125725,4.261759,3.868567e-51
43,Seraph's Embrace,4.348935,4.257448,5.275889e-48
32,Thief's Gloves,4.131840,4.261670,1.662700e-46
23,Warmog's Armor,4.124037,4.261272,5.322606e-39
13,Bloodthirster,4.138749,4.261458,7.416603e-39
20,Last Whisper,4.180782,4.262172,2.256018e-38
37,Bramble Vest,4.166677,4.261580,4.875874e-32
45,Spatula,4.510885,4.259666,1.375410e-20
15,Rabadon's Deathcap,4.308833,4.259075,5.259865e-11
31,Rapid Firecannon,4.305537,4.259267,9.366324e-09
47,Quicksilver,4.227980,4.260975,7.475602e-08
27,Spear of Shojin,4.290138,4.259415,2.661749e-05
12,Guinsoo's Rageblade,4.236294,4.260459,1.494887e-03
41,Dragon's Claw,4.233200,4.260406,1.617107e-03
11,Infinity Edge,4.252111,4.260269,1.687466e-01
22,Guardian Angel,4.265747,4.259751,2.231161e-01

p_value가 0.05 미만이면서 with_item_mean_rank가 without_item_mean_rank보다 낮은 항목들이, 만들었을 때 통계적으로 확실하게 등수 방어에 도움을 주는 1티어 아이템들입니당

### 22번: 활성화된 시너지가 우승 혹은 TOP4에 영향을 얼마나 미치는가

In [53]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
df_pivot = df_synergy.pivot_table(index=['gameid', 'user_id', 'top4_flag'], columns='synergy', values='synergy_val', fill_value=0).reset_index()

X = df_pivot.drop(['gameid', 'user_id', 'top4_flag'], axis=1)
y = df_pivot['top4_flag'].astype(int)

model = LogisticRegression(max_iter=1000)
model.fit(X, y)

coef_df = pd.DataFrame({'synergy': X.columns, 'coefficient': model.coef_[0]})
coef_df = coef_df.sort_values(by='coefficient', ascending=False)
print(coef_df)

          synergy  coefficient
19       Starship     0.849703
10      MechPilot     0.795731
20       Valkyrie     0.704219
12         Mystic     0.668723
3       Celestial     0.657129
15         Sniper     0.636026
14          Rebel     0.626854
13      Protector     0.626179
4          Chrono     0.617623
8     Infiltrator     0.613024
22           Void     0.582261
16       Sorcerer     0.568166
9      ManaReaver     0.551230
5      Cybernetic     0.547216
11      Mercenary     0.535704
2         Brawler     0.531305
18   StarGuardian     0.515395
17    SpacePirate     0.464850
6        DarkStar     0.462488
21       Vanguard     0.444558
1         Blaster     0.310968
0     Blademaster     0.260704
7   Demolitionist     0.174630

1번: 카이제곱 검정 (2x2 교차분석)
11번: 독립표본 T-검정
13번: 이항 검정 (단일 표본 비율 검정)
18번: 독립표본 T-검정
19번: 독립표본 T-검정
22번: 로지스틱 회귀 분석

## 그룹 2!

### 2번: 픽률이 높은 시너지가 반드시 높은 승률을 보인다.

In [62]:
import pandas as pd
from scipy.stats import spearmanr

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')

synergy_stats = df_synergy.groupby('synergy').agg(
    pick_count=('synergy', 'count'),
    win_rate=('ranked_1', 'mean')
).reset_index()

stat, p_value = spearmanr(synergy_stats['pick_count'], synergy_stats['win_rate'])

print(f"Spearman correlation: {stat}, p-value: {p_value}")

Spearman correlation: -0.4298418972332016, p-value: 0.040646976298646345

p_value가 0.05 미만이고 Spearman correlation이 양수(0에서 1 사이)라면, 유저들이 많이 선택하는 시너지가 실제로 승률도 높다는 뜻. 반대로 correlation이 음수라면 많이 뽑을수록 오히려 승률이 낮아진다는 의미

## 8번: 시너지별 픽률에 유의미한 차이가 있다.

In [64]:
import pandas as pd
from scipy.stats import binomtest

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')

total_boards = len(df_synergy[['gameid', 'user_id']].drop_duplicates())
synergy_counts = df_synergy['synergy'].value_counts()
mean_pick_rate = (synergy_counts / total_boards).mean()

results = []
for syn, count in synergy_counts.items():
    res = binomtest(count, n=total_boards, p=mean_pick_rate, alternative='two-sided')
    
    results.append({
        'synergy': syn,
        'pick_rate': count / total_boards,
        'mean_pick_rate': mean_pick_rate,
        'p_value': res.pvalue
    })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

          synergy  pick_rate  mean_pick_rate        p_value
0          Chrono   0.663489        0.368868   0.000000e+00
1      Cybernetic   0.530724        0.368868   0.000000e+00
2        Vanguard   0.482077        0.368868   0.000000e+00
3        DarkStar   0.477095        0.368868   0.000000e+00
4       Celestial   0.455259        0.368868   0.000000e+00
5        Valkyrie   0.450539        0.368868   0.000000e+00
6         Blaster   0.445416        0.368868   0.000000e+00
7         Brawler   0.422788        0.368868   0.000000e+00
8     Blademaster   0.414817        0.368868   0.000000e+00
9      ManaReaver   0.412483        0.368868   0.000000e+00
10          Rebel   0.400336        0.368868   0.000000e+00
15    Infiltrator   0.333931        0.368868   0.000000e+00
19      Protector   0.246342        0.368868   0.000000e+00
18   StarGuardian   0.254974        0.368868   0.000000e+00
17         Sniper   0.258679        0.368868   0.000000e+00
16      Mercenary   0.321093        0.368868   0.000000e+00
20  Demolitionist   0.227934        0.368868   0.000000e+00
21      MechPilot   0.171334        0.368868   0.000000e+00
22       Starship   0.058553        0.368868   0.000000e+00
14       Sorcerer   0.343136        0.368868  1.462279e-249
11           Void   0.392524        0.368868  2.091698e-207
13         Mystic   0.352007        0.368868  6.496198e-108
12    SpacePirate   0.368425        0.368868   5.644815e-01

출력된 표에서 p_value가 0.05 미만인 시너지들이 유의미한 픽률 차이를 보이는 항목들, pick_rate가 mean_pick_rate보다 높으면 유저들이 비정상적으로 많이 찾는 오버파워(OP) 혹은 인기 시너지라는 뜻, 낮으면 철저히 소외된 비주류 시너지라는 뜻으로 해석 가능!

## 9번: 픽률 상위 시너지가 승률도 높은가.

In [65]:
import pandas as pd
from scipy.stats import linregress

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')

synergy_stats = df_synergy.groupby('synergy').agg(
    pick_count=('synergy', 'count'),
    win_rate=('ranked_1', 'mean')
).reset_index()

res = linregress(synergy_stats['pick_count'], synergy_stats['win_rate'])

print("Slope:", res.slope)
print("R-squared:", res.rvalue**2)
print("p-value:", res.pvalue)

Slope: -1.9903762005693108e-07
R-squared: 0.34683306917976425
p-value: 0.003110423447517519

출력된 p-value가 0.05 미만이면 픽률이 승률에 유의미한 영향을 준다는 뜻
Slope(기울기) 값이 양수(+)이면 픽률이 오를수록 승률도 올라간다는 뜻이고, 음수(-)이면 픽률이 오를수록 승률은 떨어진다는 뜻으로 해석
R-squared 값은 1에 가까울수록 픽률이 승률을 아주 잘 설명한다는 뜻

## 12번: 픽률 하위임에도 승률 상위인 시너지가 통계적으로 유의미하게 존재한다. (꿀덱 찾기)

In [66]:
import pandas as pd
from scipy.stats import binomtest

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')

overall_win_rate = df_synergy['ranked_1'].mean()
synergy_counts = df_synergy['synergy'].value_counts()
low_pick_threshold = synergy_counts.quantile(0.25)

low_pick_synergies = synergy_counts[synergy_counts <= low_pick_threshold].index
results = []

for syn in low_pick_synergies:
    target_data = df_synergy[df_synergy['synergy'] == syn]
    successes = target_data['ranked_1'].sum()
    trials = len(target_data)
    
    if trials > 0:
        res = binomtest(successes, n=trials, p=overall_win_rate, alternative='greater')
        results.append({
            'synergy': syn,
            'pick_count': trials,
            'win_rate': successes / trials,
            'p_value': res.pvalue
        })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

         synergy  pick_count  win_rate        p_value
5       Starship       23200  0.202457  8.054589e-188
1   StarGuardian      101027  0.139428   2.456715e-09
3  Demolitionist       90313  0.136138   4.048414e-03
4      MechPilot       67887  0.135932   1.626603e-02
2      Protector       97607  0.134314   1.392953e-01
0         Sniper      102495  0.125352   1.000000e+00

결과 표에서 p_value가 0.05 미만으로 나온 항목이 있다면, 그 시너지는 남들이 잘 안 쓰는데도 평균을 상회하는 강력한 우승 포텐셜을 가진 진짜 꿀덱일건데 p벨류가 또

## 12번 파생: 그럼 픽률 말고 전부로 보면?

In [67]:
import pandas as pd
from scipy.stats import binomtest

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')

overall_win_rate = df_synergy['ranked_1'].mean()
results = []

for syn in df_synergy['synergy'].unique():
    target_data = df_synergy[df_synergy['synergy'] == syn]
    successes = target_data['ranked_1'].sum()
    trials = len(target_data)
    
    if trials > 0:
        res = binomtest(successes, n=trials, p=overall_win_rate, alternative='greater')
        results.append({
            'synergy': syn,
            'pick_count': trials,
            'win_rate': successes / trials,
            'overall_win_rate': overall_win_rate,
            'p_value': res.pvalue
        })

result_df = pd.DataFrame(results).sort_values(['p_value', 'pick_count'], ascending=[True, True])
display(result_df)

          synergy  pick_count  win_rate  overall_win_rate        p_value
22       Starship       23200  0.202457          0.133131  8.054589e-188
15      Mercenary      127225  0.159976          0.133131  3.806410e-166
16         Mystic      139474  0.157119          0.133131  1.751557e-146
12       Valkyrie      178515  0.138694          0.133131   3.059276e-12
18   StarGuardian      101027  0.139428          0.133131   2.456715e-09
5       Celestial      180385  0.137456          0.133131   3.712249e-08
14       DarkStar      189037  0.137238          0.133131   8.417590e-08
1   Demolitionist       90313  0.136138          0.133131   4.048414e-03
11       Sorcerer      135959  0.135158          0.133131   1.414628e-02
21      MechPilot       67887  0.135932          0.133131   1.626603e-02
17      Protector       97607  0.134314          0.133131   1.392953e-01
2     Infiltrator      132312  0.133457          0.133131   3.644595e-01
6            Void      155528  0.133429          0.133131   3.654871e-01
20     ManaReaver      163436  0.131954          0.133131   9.199903e-01
10    Blademaster      164361  0.127834          0.133131   1.000000e+00
3           Rebel      158623  0.127018          0.133131   1.000000e+00
7          Sniper      102495  0.125352          0.133131   1.000000e+00
19    SpacePirate      145979  0.125169          0.133131   1.000000e+00
4         Brawler      167519  0.120936          0.133131   1.000000e+00
8         Blaster      176485  0.125410          0.133131   1.000000e+00
13       Vanguard      191011  0.123166          0.133131   1.000000e+00
0      Cybernetic      210286  0.125467          0.133131   1.000000e+00
9          Chrono      262891  0.127098          0.133131   1.000000e+00

에라잇

## 그룹 3

### 3번: 어떤 시너지가 티어별로 선호도(픽률) 차이가 유의미하게 나는가

In [68]:
import pandas as pd
from scipy.stats import chi2_contingency

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
results = []

for syn in df_synergy['synergy'].unique():
    df_synergy['is_target'] = (df_synergy['synergy'] == syn)
    contingency = pd.crosstab(df_synergy['tier'], df_synergy['is_target'])
    
    if contingency.shape[1] == 2:
        chi2, p_value, dof, expected = chi2_contingency(contingency)
        results.append({
            'synergy': syn,
            'p_value': p_value
        })

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

          synergy        p_value
1   Demolitionist   0.000000e+00
18   StarGuardian   0.000000e+00
16         Mystic  1.483205e-310
2     Infiltrator  2.111126e-303
9          Chrono  2.928635e-275
21      MechPilot  9.003495e-214
13       Vanguard  3.765873e-192
6            Void  8.139458e-146
19    SpacePirate  3.932113e-132
17      Protector  4.337866e-131
11       Sorcerer  7.244215e-114
15      Mercenary  2.866192e-108
10    Blademaster  2.375316e-101
3           Rebel   1.216069e-93
0      Cybernetic   8.783916e-78
7          Sniper   2.844131e-54
12       Valkyrie   4.229856e-49
4         Brawler   6.881067e-33
14       DarkStar   1.752264e-31
8         Blaster   2.225422e-28
22       Starship   4.612195e-13
20     ManaReaver   7.118562e-12
5       Celestial   7.291731e-11

p_value가 0.05 미만인 시너지는 티어에 따라 유저들의 픽률이 확연히 달라지는 시너지. 특정 티어 구간에서만 유행하거나, 반대로 특정 구간에서는 기피되는 시너지

### 4번: 티어가 높을수록 평균 생존 라운드가 길다

In [71]:
import pandas as pd
from scipy.stats import spearmanr

# lastround가 존재하는 match 데이터 로드
df_match = pd.read_csv('게임단위_게임데이터_상위랭커보존-2차 전처리 완료(match).csv')

tier_mapping = {'platinum': 1, 'diamond': 2, 'master': 3, 'grand_master': 4, 'challenger': 5}
df_match['tier_num'] = df_match['tier'].map(tier_mapping)

df_valid = df_match.dropna(subset=['tier_num', 'lastround'])

stat, p_value = spearmanr(df_valid['tier_num'], df_valid['lastround'])
print("Spearman correlation:", stat)
print("p-value:", p_value)

Spearman correlation: 0.027750445750244417
p-value: 2.144349420131245e-68

결과의 p_value가 0.05 미만이고 상관계수(correlation)가 양수라면, 플래티넘에서 챌린저로 갈수록 게임이 늦게 끝나고 평균 생존 라운드가 길어진다는 가설이 입증됨

### 10번: 고티어에서만 유독 승률이 잘 나오는 시너지가 있는가

In [72]:
import pandas as pd
from scipy.stats import spearmanr

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
tier_mapping = {'IRON': 1, 'BRONZE': 2, 'SILVER': 3, 'GOLD': 4, 'PLATINUM': 5, 'EMERALD': 6, 'DIAMOND': 7, 'MASTER': 8, 'GRANDMASTER': 9, 'CHALLENGER': 10}
df_synergy['tier_num'] = df_synergy['tier'].str.upper().map(tier_mapping)
df_valid = df_synergy.dropna(subset=['tier_num', 'top4_flag'])

results = []
for syn in df_valid['synergy'].unique():
    syn_data = df_valid[df_valid['synergy'] == syn]
    if len(syn_data) > 30:
        stat, p = spearmanr(syn_data['tier_num'], syn_data['top4_flag'])
        results.append({
            'synergy': syn, 
            'correlation': stat, 
            'p_value': p
        })

result_df = pd.DataFrame(results).dropna().sort_values('correlation', ascending=False)
display(result_df)

          synergy  correlation       p_value
22       Starship     0.075512  1.236395e-24
16         Mystic     0.022782  2.168348e-14
18   StarGuardian     0.022707  1.348355e-10
10    Blademaster     0.021103  1.671075e-14
13       Vanguard     0.011448  8.514717e-06
17      Protector     0.007867  2.685840e-02
3           Rebel     0.006207  2.795070e-02
20     ManaReaver     0.003309  2.325092e-01
8         Blaster     0.003193  2.309214e-01
1   Demolitionist     0.002001  5.840788e-01
5       Celestial     0.001010  7.013603e-01
14       DarkStar    -0.000106  9.671556e-01
19    SpacePirate    -0.001224  6.783610e-01
9          Chrono    -0.003562  1.070013e-01
7          Sniper    -0.004459  1.999587e-01
21      MechPilot    -0.006167  1.433001e-01
11       Sorcerer    -0.006869  2.323333e-02
4         Brawler    -0.007185  8.765486e-03
15      Mercenary    -0.009712  2.049949e-03
12       Valkyrie    -0.013155  6.699858e-07
0      Cybernetic    -0.013543  3.435170e-08
2     Infiltrator    -0.020722  9.199013e-12
6            Void    -0.021085  2.152025e-13

p_value가 0.05 미만이면서 correlation 값이 양수인 시너지가 고티어 전용 덱. 초보자 구간에서는 승률이 낮지만 장인들이 모인 고티어로 갈수록 성능이 제대로 나오는 난이도 높은 시너지라고 볼 수 있다. 근데 p벨류가 또 허허

### 15번: 티어가 올라갈수록 픽률이 높은 시너지가 어떻게 바뀌는가

In [73]:
import pandas as pd

df_synergy = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_combination_1.csv')
pick_rates = df_synergy.groupby(['tier', 'synergy']).size().reset_index(name='count')
tier_totals = df_synergy.groupby('tier').size().reset_index(name='total')

merged = pd.merge(pick_rates, tier_totals, on='tier')
merged['pick_rate'] = merged['count'] / merged['total']

top_synergies = merged.sort_values(['tier', 'pick_rate'], ascending=[True, False]).groupby('tier').head(3)
display(top_synergies)

            tier     synergy  count   total  pick_rate
4     challenger      Chrono  49856  670196   0.074390
5     challenger  Cybernetic  42267  670196   0.063067
21    challenger    Vanguard  40564  670196   0.060526
27       diamond      Chrono  56554  689813   0.081985
28       diamond  Cybernetic  44308  689813   0.064232
29       diamond    DarkStar  38044  689813   0.055151
50  grand_master      Chrono  58124  681997   0.085226
51  grand_master  Cybernetic  44310  681997   0.064971
67  grand_master    Vanguard  39792  681997   0.058346
73        master      Chrono  52686  671438   0.078467
74        master  Cybernetic  42010  671438   0.062567
90        master    Vanguard  39993  671438   0.059563
96      platinum      Chrono  45671  648111   0.070468
98      platinum    DarkStar  38322  648111   0.059129
97      platinum  Cybernetic  37391  648111   0.057692

메타 변화를 직관적으로 확인

### 17번: 티어와 관계없이 언제나 성과가 좋은 국밥 챔피언 찾기

In [74]:
import pandas as pd
from scipy.stats import f_oneway

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
results = []

for champ in df_champ['champion_name'].unique():
    champ_data = df_champ[df_champ['champion_name'] == champ]
    tier_groups = [group['ranked'].values for name, group in champ_data.groupby('tier') if len(group) > 5]
    
    if len(tier_groups) > 1:
        stat, p = f_oneway(*tier_groups)
        results.append({
            'champion': champ,
            'mean_rank': champ_data['ranked'].mean(),
            'p_value': p
        })

result_df = pd.DataFrame(results).sort_values('mean_rank')
display(result_df)

       champion  mean_rank       p_value
48  aurelionsol   3.538565  4.650570e-35
47         lulu   3.602905  1.737547e-01
38       thresh   3.781538  5.141125e-03
13  missfortune   3.869822  2.409213e-24
3          ekko   3.882404  3.448885e-11
51       xerath   3.892201  1.753429e-01
43    gangplank   4.094361  5.537119e-02
19       soraka   4.211661  7.725771e-06
2       chogath   4.252087  6.106571e-31
26          lux   4.256409  5.704502e-01
8         kayle   4.270052  2.738156e-02
10       velkoz   4.287727  3.539465e-01
7            vi   4.320580  8.623019e-17
49         fizz   4.332169  1.887759e-13
37         jinx   4.345225  1.879734e-03
12        karma   4.361824  5.457739e-05
35     malphite   4.366932  2.631936e-05
40     kassadin   4.377646  8.294877e-24
25       ezreal   4.380929  3.268145e-15
1          ashe   4.389839  8.634499e-14
16        rakan   4.394848  3.117675e-06
36       irelia   4.401427  3.965545e-07
34       graves   4.404048  3.634576e-19
9        wukong   4.408284  1.731960e-01
23   blitzcrank   4.412536  4.508803e-36
15        xayah   4.439643  2.183391e-14
27         jhin   4.443615  3.013834e-09
44        annie   4.445936  3.528265e-08
45       rumble   4.473334  6.368309e-10
20  twistedfate   4.474582  1.735875e-02
22     jarvaniv   4.495818  1.807357e-19
11        shaco   4.515834  4.763894e-10
21      caitlyn   4.517704  6.005306e-12
24         shen   4.529056  2.527471e-10
17      xinzhao   4.533292  9.924687e-02
4         fiora   4.534028  1.380682e-21
29          zoe   4.535486  5.152235e-01
31        neeko   4.542903  2.329536e-04
33        kaisa   4.552828  4.177313e-16
32       syndra   4.561548  2.478256e-02
30         ahri   4.578288  3.574290e-03
42        jayce   4.580139  1.151549e-01
39       khazix   4.589764  1.822565e-21
50         sona   4.649165  5.301864e-16
6        lucian   4.661789  3.990998e-25
14        poppy   4.687450  1.319930e-03
41       darius   4.687496  1.242968e-07
5         leona   4.694774  1.843429e-21
18  mordekaiser   4.744424  1.724693e-12
46     masteryi   4.898830  4.065566e-02
28        yasuo   4.938348  1.906797e-02
0         ziggs   4.970338  2.581602e-03

분산분석(ANOVA)에서 p-value가 0.05 이상이라는 건 그룹 간(티어 간) 평균 등수 차이가 통계적으로 없다는 뜻이니까, 플래티넘부터 챌린저 구간 전체에서 등수 차이가 없다는 뜻

## 그룹 4

### 5번: 3성 챔피언을 보유한 경우 평균 등수가 유의미하게 낮다(좋다).

In [75]:
import pandas as pd
from scipy.stats import ttest_ind

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

player_stats = df_champ.groupby(['gameid', 'user_id']).agg(
    max_star=('star', 'max'),
    ranked=('ranked', 'first')
).reset_index()

has_3_star = player_stats[player_stats['max_star'] >= 3]['ranked']
no_3_star = player_stats[player_stats['max_star'] < 3]['ranked']

stat, p_value = ttest_ind(has_3_star, no_3_star, equal_var=False)

print(has_3_star.mean())
print(no_3_star.mean())
print(p_value)

3.916237535047846
5.085489513144639
0.0

1. 有 평균 등수 2. 無 평균 등수 3. p-value

### 문제 5-1: 티어별 3성 효율 차이

In [76]:
import pandas as pd
from scipy.stats import ttest_ind

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

player_stats = df_champ.groupby(['gameid', 'user_id', 'tier']).agg(
    max_star=('star', 'max'),
    ranked=('ranked', 'first')
).reset_index()

tier_order = ['platinum', 'diamond', 'master', 'grand_master', 'challenger']
results = []

for t in tier_order:
    tier_data = player_stats[player_stats['tier'] == t]
    
    has_3_star = tier_data[tier_data['max_star'] >= 3]['ranked']
    no_3_star = tier_data[tier_data['max_star'] < 3]['ranked']
    
    if len(has_3_star) > 1 and len(no_3_star) > 1:
        stat, p_value = ttest_ind(has_3_star, no_3_star, equal_var=False)
        
        results.append({
            'tier': t,
            'has_3_star_mean_rank': has_3_star.mean(),
            'no_3_star_mean_rank': no_3_star.mean(),
            'rank_diff': no_3_star.mean() - has_3_star.mean(),
            'p_value': p_value
        })

result_df = pd.DataFrame(results)
result_df['tier'] = pd.Categorical(result_df['tier'], categories=tier_order, ordered=True)
result_df = result_df.sort_values('tier')
display(result_df)

           tier  has_3_star_mean_rank  no_3_star_mean_rank  rank_diff  p_value
0      platinum              3.926781             5.281512   1.354732      0.0
1       diamond              3.998360             5.137689   1.139329      0.0
2        master              3.873367             5.087783   1.214416      0.0
3  grand_master              3.923339             4.989377   1.066038      0.0
4    challenger              3.836607             4.994967   1.158360      0.0

### 5-2번: 챔피언 코스트별 3성 가치 차이

In [77]:
import pandas as pd
from scipy.stats import f_oneway

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

# 3성 챔피언 데이터만 추출
df_3_star = df_champ[df_champ['star'] == 3].copy()

# 코스트별 등수 데이터를 담을 리스트
cost_groups = []
results = []

# 코스트(1~5)별로 순회
for cost in sorted(df_3_star['cost'].dropna().unique()):
    ranks = df_3_star[df_3_star['cost'] == cost]['ranked']
    
    if len(ranks) > 0:
        cost_groups.append(ranks.values)
        results.append({
            'cost': cost,
            '3_star_count': len(ranks),
            'mean_rank': ranks.mean()
        })

# 코스트 간 등수 차이가 유의미한지 분산분석(ANOVA) 진행
if len(cost_groups) > 1:
    stat, p_value = f_oneway(*cost_groups)
else:
    p_value = None

print(f"ANOVA p-value: {p_value}\n")

result_df = pd.DataFrame(results)
display(result_df)

ANOVA p-value: 0.0

   cost  3_star_count  mean_rank
0     1        142215   4.072390
1     2        156885   3.712331
2     3        107220   3.081076
3     4         23470   1.908308
4     5            91   1.362637

뭐든 3성작만 하면 순방을 노릴 수는 있겠다!

### 5-3번: 3성 기물의 개수와 승률의 관계

In [78]:
import pandas as pd
from scipy.stats import f_oneway

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

df_champ['is_3_star'] = (df_champ['star'] == 3).astype(int)

player_stats = df_champ.groupby(['gameid', 'user_id']).agg(
    num_3_stars=('is_3_star', 'sum'),
    ranked=('ranked', 'first')
).reset_index()

player_stats['num_3_stars_grouped'] = player_stats['num_3_stars'].apply(lambda x: x if x < 4 else 4)

results = []
groups = []

for num in sorted(player_stats['num_3_stars_grouped'].unique()):
    ranks = player_stats[player_stats['num_3_stars_grouped'] == num]['ranked']
    
    if len(ranks) > 0:
        groups.append(ranks.values)
        results.append({
            'num_3_stars': f"{num}개" if num < 4 else "4개 이상",
            'player_count': len(ranks),
            'mean_rank': ranks.mean()
        })

if len(groups) > 1:
    stat, p_value = f_oneway(*groups)
else:
    p_value = None

print(f"ANOVA p-value: {p_value}\n")

result_df = pd.DataFrame(results)
display(result_df)

ANOVA p-value: 0.0

  num_3_stars  player_count  mean_rank
0          0개        197533   5.085490
1          1개         78423   4.399067
2          2개         50239   4.179661
3          3개         39096   3.597376
4       4개 이상         30899   2.665944

### 5-3-2번: 티어가 올라갈수록 평균 3성 챔피언 보유 개수가 늘어나는가

In [79]:
import pandas as pd
from scipy.stats import f_oneway

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

df_champ['is_3_star'] = (df_champ['star'] == 3).astype(int)

player_stats = df_champ.groupby(['gameid', 'user_id', 'tier']).agg(
    num_3_stars=('is_3_star', 'sum')
).reset_index()

tier_order = ['platinum', 'diamond', 'master', 'grand_master', 'challenger']
player_stats['tier'] = pd.Categorical(player_stats['tier'], categories=tier_order, ordered=True)

tier_means = player_stats.groupby('tier', observed=True)['num_3_stars'].mean().reset_index()
tier_means.rename(columns={'num_3_stars': 'avg_3_stars_per_player'}, inplace=True)

groups = [group['num_3_stars'].values for name, group in player_stats.groupby('tier', observed=True) if len(group) > 0]

if len(groups) > 1:
    stat, p_value = f_oneway(*groups)
else:
    p_value = None

print(f"ANOVA p-value: {p_value}\n")
display(tier_means)

ANOVA p-value: 0.0

           tier  avg_3_stars_per_player
0      platinum                1.180921
1       diamond                1.223319
2        master                1.063198
3  grand_master                1.036109
4    challenger                0.926020

확실히 티어가 오를수록 견제를 할 줄 안다

### 5-4 3성작이 강제되는 챔피언이 있을까?

In [80]:
import pandas as pd
from scipy.stats import ttest_ind

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
results = []

for champ in df_champ['champion_name'].dropna().unique():
    champ_data = df_champ[df_champ['champion_name'] == champ]
    
    star2 = champ_data[champ_data['star'] == 2]['ranked']
    star3 = champ_data[champ_data['star'] == 3]['ranked']
    
    if len(star2) > 5 and len(star3) > 5:
        stat, p_value = ttest_ind(star2, star3, equal_var=False)
        
        results.append({
            'champion': champ,
            '2_star_mean_rank': star2.mean(),
            '3_star_mean_rank': star3.mean(),
            'rank_diff': star2.mean() - star3.mean(),
            'p_value': p_value
        })

result_df = pd.DataFrame(results).sort_values('rank_diff', ascending=False)
display(result_df)

c:\Users\asdxo\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\stats\_axis_nan_policy.py:592: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

       champion  2_star_mean_rank  3_star_mean_rank  rank_diff        p_value
8         kayle          4.092331          1.677983   2.414348   0.000000e+00
10       velkoz          4.124390          1.776901   2.347489   0.000000e+00
36       irelia          4.233517          1.899772   2.333745   0.000000e+00
9        wukong          4.052532          1.732849   2.319683   0.000000e+00
37         jinx          4.188094          1.980783   2.207312   0.000000e+00
49         fizz          4.031804          1.911546   2.120258   0.000000e+00
2       chogath          4.025550          1.949981   2.075568   0.000000e+00
27         jhin          4.265356          2.217305   2.048050   0.000000e+00
19       soraka          3.902464          1.911864   1.990600  2.090769e-158
11        shaco          5.028845          3.042017   1.986828   0.000000e+00
51       xerath          2.973967          1.000000   1.973967   0.000000e+00
45       rumble          4.986045          3.069546   1.916498   0.000000e+00
42        jayce          4.846225          2.967288   1.878937   0.000000e+00
41       darius          5.538630          3.717118   1.821513   0.000000e+00
31        neeko          4.975158          3.178505   1.796653   0.000000e+00
13  missfortune          2.906011          1.125000   1.781011   1.193083e-12
47         lulu          2.715959          1.000000   1.715959   0.000000e+00
43    gangplank          3.171550          1.458333   1.713217   7.476693e-07
48  aurelionsol          2.805713          1.111111   1.694602   2.196491e-07
33        kaisa          5.208392          3.515736   1.692656   0.000000e+00
32       syndra          4.992971          3.395293   1.597678   0.000000e+00
40     kassadin          4.344583          2.756212   1.588371   0.000000e+00
1          ashe          4.389451          2.863263   1.526188   0.000000e+00
46     masteryi          5.177098          3.736011   1.441087   0.000000e+00
17      xinzhao          5.260768          3.828085   1.432683   0.000000e+00
44        annie          4.931571          3.560731   1.370841   0.000000e+00
3          ekko          3.030219          1.666667   1.363552   5.537914e-04
7            vi          4.246700          2.943889   1.302811   0.000000e+00
26          lux          4.184320          2.929397   1.254923  3.308240e-231
25       ezreal          4.286802          3.036672   1.250130   0.000000e+00
30         ahri          4.814627          3.590357   1.224269   0.000000e+00
16        rakan          4.834436          3.690335   1.144101   0.000000e+00
22     jarvaniv          5.028251          3.891004   1.137248   0.000000e+00
21      caitlyn          4.981261          3.892218   1.089042  8.788192e-254
12        karma          4.338768          3.251411   1.087357  5.098895e-149
28        yasuo          5.226200          4.221513   1.004687  5.928668e-218
18  mordekaiser          4.823569          3.857869   0.965700  1.232585e-281
50         sona          4.885281          3.944744   0.940537  1.193007e-302
24         shen          4.540160          3.604339   0.935820   0.000000e+00
23   blitzcrank          4.335342          3.411982   0.923359  7.255889e-174
15        xayah          4.775856          3.920524   0.855332   0.000000e+00
38       thresh          2.856010          2.100000   0.756010   1.334639e-01
39       khazix          4.714667          3.985351   0.729316  4.529252e-203
6        lucian          4.574968          3.862920   0.712048   1.032251e-85
20  twistedfate          4.680845          4.046816   0.634029  2.948484e-140
14        poppy          4.749265          4.200275   0.548990  6.019416e-125
0         ziggs          5.229438          4.696087   0.533351   1.412189e-33
34       graves          4.335314          3.894255   0.441059   9.992410e-38
4         fiora          4.558378          4.141331   0.417047   1.148067e-52
35     malphite          4.324285          4.034827   0.289458   7.345939e-36
29          zoe          4.556240          4.278484   0.277756   1.603939e-27
5         leona          4.656273          4.590890   0.065384   2.583269e-02

p_value: 0.05 미만이면 2성일 때와 3성일 때의 등수 차이가 통계적으로 확실하다는 뜻

rank_diff: 이 숫자가 클수록 3성을 찍었을 때 등수가 극적으로 수직 상승한다는 뜻

### 6번: 챔피언 비용(cost)과 평균 등수 사이에 상관관계가 있다.

In [83]:
import pandas as pd
from scipy.stats import spearmanr

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
df_valid = df_champ.dropna(subset=['cost', 'ranked'])

stat, p_value = spearmanr(df_valid['cost'], df_valid['ranked'])

print(stat)
print(p_value)

-0.07743384155557943
0.0

출력된 p_value가 0.05 미만이고 첫 번째 숫자인 stat(상관계수)가 음수(-)로 나오면, 코스트가 높은 비싼 챔피언을 덱에 많이 넣을수록 등수가 1등에 가까워진다는 고밸류 덱의 위력이 통계적으로 증명

### 7번: 같은 코스트 내에서도 챔피언 간에 유의미한 평균 등수 차이가 존재한다

In [84]:
import pandas as pd
from scipy.stats import kruskal

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
df_valid = df_champ.dropna(subset=['cost', 'champion_name', 'ranked'])

results = []

# 코스트별로 순회 (1 ~ 5 코스트)
for cost in sorted(df_valid['cost'].unique()):
    cost_data = df_valid[df_valid['cost'] == cost]
    
    champ_groups = []
    champ_names = []
    
    # 해당 코스트 내의 챔피언별로 데이터 그룹화
    for champ, group in cost_data.groupby('champion_name'):
        if len(group) > 30: # 표본이 너무 적은 챔피언은 제외 (신뢰도 확보)
            champ_groups.append(group['ranked'].values)
            champ_names.append(champ)
    
    # 비교할 챔피언이 2명 이상일 때만 검정 수행
    if len(champ_groups) > 1:
        stat, p_value = kruskal(*champ_groups)
        
        # 챔피언별 평균 등수 계산
        mean_ranks = cost_data.groupby('champion_name')['ranked'].mean().reset_index()
        mean_ranks = mean_ranks[mean_ranks['champion_name'].isin(champ_names)]
        
        # 가장 좋은 챔피언 (등수 숫자가 가장 작음)
        best_champ = mean_ranks.loc[mean_ranks['ranked'].idxmin()]
        # 가장 나쁜 챔피언 (등수 숫자가 가장 큼)
        worst_champ = mean_ranks.loc[mean_ranks['ranked'].idxmax()]
        
        results.append({
            'cost': cost,
            'p_value': p_value,
            'best_champion': best_champ['champion_name'],
            'best_mean_rank': best_champ['ranked'],
            'worst_champion': worst_champ['champion_name'],
            'worst_mean_rank': worst_champ['ranked']
        })

result_df = pd.DataFrame(results)
display(result_df)

,cost,p_value,best_champion,best_mean_rank,worst_champion,worst_mean_rank
0,1,0.000000e+00,malphite,4.366932,ziggs,4.970338
1,2,0.000000e+00,rakan,4.394848,yasuo,4.938348
2,3,0.000000e+00,lux,4.256409,masteryi,4.898830
3,4,4.655139e-148,soraka,4.211661,jhin,4.443615
4,5,0.000000e+00,aurelionsol,3.538565,gangplank,4.094361

### 14번: 플레이어의 최종 레벨이 높을수록 평균 등수가 높다.

In [82]:
import pandas as pd
from scipy.stats import spearmanr

df_match = pd.read_csv('게임단위_게임데이터_상위랭커보존-2차 전처리 완료(match).csv')
df_valid = df_match.dropna(subset=['level', 'ranked'])

stat, p_value = spearmanr(df_valid['level'], df_valid['ranked'])

print("Spearman correlation:", stat)
print("p-value:", p_value)

Spearman correlation: -0.4860139545327237
p-value: 0.0

p_value가 0.05 미만이고 Spearman correlation 값이 음수(-)로 나오면 레벨업이 순위 방어에 핵심적인 역할을 한다는 가설이 입증됨

### 16번: 같은 챔피언이라도 성급(star)에 따라 등수가 유의미하게 다르다.

In [85]:
import pandas as pd
from scipy.stats import f_oneway

df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')
results = []

for champ in df_champ['champion_name'].dropna().unique():
    champ_data = df_champ[df_champ['champion_name'] == champ]
    
    star_groups = []
    mean_ranks = {}
    
    for star in sorted(champ_data['star'].dropna().unique()):
        ranks = champ_data[champ_data['star'] == star]['ranked']
        
        if len(ranks) > 5:
            star_groups.append(ranks.values)
            mean_ranks[f'star_{int(star)}_mean_rank'] = ranks.mean()
            
    if len(star_groups) > 1:
        stat, p_value = f_oneway(*star_groups)
        
        res_dict = {
            'champion': champ,
            'p_value': p_value
        }
        res_dict.update(mean_ranks)
        results.append(res_dict)

result_df = pd.DataFrame(results).sort_values('p_value')
display(result_df)

,champion,p_value,star_1_mean_rank,star_2_mean_rank,star_3_mean_rank
1,ashe,0.000000e+00,5.523359,4.389451,2.863263
2,chogath,0.000000e+00,5.730993,4.025550,1.949981
3,ekko,0.000000e+00,4.390798,3.030219,1.666667
7,vi,0.000000e+00,5.463121,4.246700,2.943889
6,lucian,0.000000e+00,5.311679,4.574968,3.862920
10,velkoz,0.000000e+00,5.902352,4.124390,1.776901
9,wukong,0.000000e+00,5.807226,4.052532,1.732849
8,kayle,0.000000e+00,5.231973,4.092331,1.677983
13,missfortune,0.000000e+00,4.415938,2.906011,1.125000
15,xayah,0.000000e+00,4.931792,4.775856,3.920524
11,shaco,0.000000e+00,6.191627,5.028845,3.042017
21,caitlyn,0.000000e+00,5.579093,4.981261,3.892218
19,soraka,0.000000e+00,5.264726,3.902464,1.911864
18,mordekaiser,0.000000e+00,5.592138,4.823569,3.857869
17,xinzhao,0.000000e+00,5.252672,5.260768,3.828085
16,rakan,0.000000e+00,5.389420,4.834436,3.690335
31,neeko,0.000000e+00,5.628322,4.975158,3.178505
25,ezreal,0.000000e+00,5.417761,4.286802,3.036672
26,lux,0.000000e+00,5.028596,4.184320,2.929397
27,jhin,0.000000e+00,5.981945,4.265356,2.217305
30,ahri,0.000000e+00,5.764517,4.814627,3.590357
22,jarvaniv,0.000000e+00,5.572075,5.028251,3.891004
23,blitzcrank,0.000000e+00,5.102407,4.335342,3.411982
24,shen,0.000000e+00,5.425661,4.540160,3.604339
40,kassadin,0.000000e+00,5.460325,4.344583,2.756212
41,darius,0.000000e+00,6.141001,5.538630,3.717118
39,khazix,0.000000e+00,5.417710,4.714667,3.985351
38,thresh,0.000000e+00,4.229182,2.856010,2.100000
36,irelia,0.000000e+00,5.905086,4.233517,1.899772
37,jinx,0.000000e+00,6.122289,4.188094,1.980783
33,kaisa,0.000000e+00,5.439224,5.208392,3.515736
32,syndra,0.000000e+00,5.736653,4.992971,3.395293
51,xerath,0.000000e+00,4.471968,2.973967,1.000000
45,rumble,0.000000e+00,5.451693,4.986045,3.069546
42,jayce,0.000000e+00,6.088668,4.846225,2.967288
43,gangplank,0.000000e+00,4.754893,3.171550,1.458333
46,masteryi,0.000000e+00,5.482930,5.177098,3.736011
47,lulu,0.000000e+00,4.082698,2.715959,1.000000
49,fizz,0.000000e+00,6.086911,4.031804,1.911546
48,aurelionsol,0.000000e+00,4.086809,2.805713,1.111111
44,annie,0.000000e+00,5.427507,4.931571,3.560731
50,sona,4.910955e-316,4.916783,4.885281,3.944744
14,poppy,6.401913e-311,5.686808,4.749265,4.200275
34,graves,3.140767e-251,5.108983,4.335314,3.894255
28,yasuo,2.846788e-248,5.422131,5.226200,4.221513
35,malphite,2.670335e-247,4.989733,4.324285,4.034827
12,karma,1.403870e-231,4.798379,4.338768,3.251411
20,twistedfate,1.043348e-213,5.175766,4.680845,4.046816
29,zoe,2.691563e-117,5.401080,4.556240,4.278484
4,fiora,1.579166e-105,4.913932,4.558378,4.141331
5,leona,7.720124e-35,4.993688,4.656273,4.590890
0,ziggs,3.160101e-34,4.859638,5.229438,4.696087

"과연 이 챔피언한테 돈과 운을 투자해서 성급(별)을 올릴 가치가 통계적으로 있는가?" 를 확인하는 것

p 벨류가 0.05 미만이면 "이 챔피언은 성급을 올릴수록 등수가 확실하게 달라진다"는 뜻

성급별 평균 등수 비교: 결과 표를 보면 star_1_mean_rank, star_2_mean_rank, star_3_mean_rank 컬럼을 만듦.
예를 들어 어떤 챔피언은 1성에서 2성으로 갈 때는 등수가 확 좋아지는데, 2성에서 3성으로 갈 때는 등수 차이가 거의 안 난다면? 그 챔피언은 무리해서 3성작을 할 필요 없이 2성까지만 찍고 다른 곳에 돈을 쓰는 게 훨씬 이득이라는 결론을 내릴 수 있다!

## 그룹 5

### 20번: 소수 정예 고단계 시너지(깊게) vs 다수 저단계 시너지(넓게)의 승률/순방률 비교

In [86]:
import pandas as pd
from scipy.stats import ttest_ind
import ast

df_match = pd.read_csv('게임단위_게임데이터_상위랭커보존-2차 전처리 완료(match).csv')

def count_syn(x):
    if pd.isna(x):
        return 0
    if isinstance(x, str):
        if x.startswith('['):
            try:
                return len(ast.literal_eval(x))
            except:
                return len(x.split(','))
        return len(x.split(','))
    return 1

df_match['syn_count'] = df_match['combination'].apply(count_syn)

median_syn = df_match['syn_count'].median()

deep_deck = df_match[df_match['syn_count'] < median_syn]
wide_deck = df_match[df_match['syn_count'] > median_syn]

stat, p_value = ttest_ind(deep_deck['ranked'], wide_deck['ranked'], equal_var=False)

print(deep_deck['ranked'].mean())
print(wide_deck['ranked'].mean())

print(deep_deck['top4_flag'].mean())
print(wide_deck['top4_flag'].mean())

print(p_value)

5.358234832182595
4.01318611953632
0.3397856261409646
0.5907916486126491
0.0

위에서부터 
소수 정예(깊은 시너지) 덱의 평균 등수

다수 혼합(넓은 시너지) 덱의 평균 등수

소수 정예 덱의 평균 순방률 (0.5면 50%)

다수 혼합 덱의 평균 순방률

p-value

데이터에 있는 모든 유저가 활성화한 시너지 개수의 중간 위치를 구한 뒤, 그 중앙값보다 켜진 시너지 개수가 적으면 한두 개 시너지에 집중한 소수 정예 덱으로 분류하고, 중앙값보다 시너지 개수가 많으면 여러 개를 섞은 다수 혼합 덱으로 분류하도록 기준을 세웠는데, 근데 뭔가뭔가 중앙값도 평균도 다 쓰면 안될거같은데....

### 21번: 같은 조합(시너지)이라도 어떤 챔피언을 메인 딜러/탱커로 쓰느냐에 따라 승률이 다르다

In [87]:
import pandas as pd
from scipy.stats import f_oneway
import ast

df_match = pd.read_csv('게임단위_게임데이터_상위랭커보존-2차 전처리 완료(match).csv')
df_champ = pd.read_csv('게임단위_게임데이터_상위랭커보존-explode_champion_1.csv')

top_comp = df_match['combination'].value_counts().idxmax()
target_users = df_match[df_match['combination'] == top_comp][['gameid', 'user_id', 'ranked']]

df_target_champ = pd.merge(df_champ, target_users, on=['gameid', 'user_id', 'ranked'])

def count_items(x):
    if pd.isna(x):
        return 0
    if isinstance(x, str):
        x = x.strip()
        if x == '[]' or x == '':
            return 0
        if x.startswith('['):
            try:
                return len(ast.literal_eval(x))
            except:
                return len(x.split(','))
        return len(x.split(','))
    if isinstance(x, list):
        return len(x)
    return 1

df_target_champ['item_count'] = df_target_champ['items'].apply(count_items)

main_carries = df_target_champ[df_target_champ['item_count'] >= 2]

results = []
groups = []

for champ in main_carries['champion_name'].unique():
    ranks = main_carries[main_carries['champion_name'] == champ]['ranked']
    if len(ranks) > 10:
        groups.append(ranks.values)
        results.append({
            'main_carry': champ,
            'player_count': len(ranks),
            'mean_rank': ranks.mean()
        })

if len(groups) > 1:
    stat, p_value = f_oneway(*groups)
else:
    p_value = None

print(top_comp)
print(p_value)

result_df = pd.DataFrame(results).sort_values('mean_rank')
display(result_df)

{'Blaster': 4, 'Chrono': 2, 'Cybernetic': 1, 'Mercenary': 1, 'Rebel': 2, 'Set3_Brawler': 4, 'Set3_Void': 1, 'SpacePirate': 1, 'Valkyrie': 1}
9.252122104969611e-118

    main_carry  player_count  mean_rank
6   blitzcrank           222   3.536036
5     malphite           147   3.673469
7       graves           414   3.840580
4       ezreal          3638   4.021990
1      chogath          5418   4.176080
3           vi          4162   4.228015
2  missfortune         11352   4.510571
0         jinx         14155   4.628329

제일 먼저 출력되는 문자열이 이번 분석의 타겟이 된 가장 유행하는 1티어 덱의 이름(조합)!

p_value가 0.05 미만이면 같은 덱을 하더라도 누구한테 템을 주느냐에 따라 승패가 완전히 갈린다는 뜻.

출력된 표에서 mean_rank가 가장 낮은(1등에 가까운) 챔피언이 그 덱의 진정한 핵심 캐리 기물이고, 반대로 mean_rank가 높은 챔피언은 템을 주면 안 되는 함정 기물이라는 걸 알 수 있다! 아마도...

끝!

1번: 독립표본 T-검정 또는 일원분산분석(ANOVA) (특정 시너지 조합 승률 유의성)
2번: 스피어만 상관계수 (픽률과 승률 간의 상관관계)
3번: 카이제곱 검정 (티어별 선호 시너지 조합 차이)
4번: 스피어만 상관계수 (티어가 높을수록 생존 라운드가 길다)
5번: 독립표본 T-검정 (3성 챔피언 보유 시 평균 등수 차이)
5-1번: 독립표본 T-검정 (티어별 3성 효율 차이)
5-2번: 일원분산분석(ANOVA) (챔피언 코스트별 3성 가치 차이)
5-3번: 일원분산분석(ANOVA) (3성 기물의 개수와 승률의 관계)
5-3-2번: 일원분산분석(ANOVA) (티어별 평균 3성 보유 개수 차이)
5-4번: 독립표본 T-검정 (3성작이 강제되는 챔피언 찾기)
6번: 스피어만 상관계수 (챔피언 비용과 평균 등수 상관관계)
7번: 크루스칼-왈리스 검정 (같은 코스트 내 챔피언 간 성능 차이)
10번: 스피어만 상관계수 (고티어에서만 강한 시너지 존재 여부)
14번: 스피어만 상관계수 (최종 레벨이 높을수록 등수가 낮다)
15번: 기술 통계 및 비율 계산 (티어별 픽률 높은 시너지 변화 확인)
16번: 일원분산분석(ANOVA) (같은 챔피언의 성급에 따른 등수 차이)
17번: 일원분산분석(ANOVA) (티어와 관계없이 일관된 성과를 내는 챔피언)
20번: 독립표본 T-검정 (소수 정예 고단계 vs 다수 혼합 저단계 시너지)
21번: 일원분산분석(ANOVA) (같은 조합 내 메인 딜러/탱커에 따른 승률 차이)